In [7]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import json
import re
import random
import time
from urllib.parse import urljoin
import warnings

warnings.filterwarnings("ignore")

In [9]:
HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/138.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "en-US,en;q=0.9"
}

BASE_URL = "https://www.carwale.com"

In [11]:
def get_soup(url):

    response = requests.get(url, headers=HEADERS)

    if response.status_code == 200:
        return BeautifulSoup(response.text, "html.parser")

    print("Failed :", url)
    return None

In [13]:
def get_brand_urls():

    soup = get_soup(BASE_URL + "/new-cars/")

    brand_urls = set()

    for tag in soup.find_all("a", href=True):

        href = tag["href"]

        if not re.fullmatch(r"/[a-z0-9-]+-cars/", href):
            continue

        brand_urls.add(BASE_URL + href)

    return sorted(brand_urls)

In [15]:
brand_urls = get_brand_urls()

print("Total Brands :", len(brand_urls))

Total Brands : 38

In [17]:
def get_car_urls(brand_url):

    soup = get_soup(brand_url)

    car_urls = set()

    brand_slug = brand_url.rstrip("/").split("/")[-1]

    bad_words = [
        "price-in",
        "expert-reviews",
        "images",
        "videos",
        "news",
        "old-generation",
        "prime",
        "jtp",
        "genx",
        "2011","2012","2013","2014","2015",
        "2016","2017","2018","2019",
        "2020","2021","2022","2023","2024",
        "1991"
    ]

    for tag in soup.find_all("a", href=True):

        href = tag["href"]

        if not href.startswith(f"/{brand_slug}/"):
            continue

        if href.count("/") != 3:
            continue

        if "#" in href or "?" in href:
            continue

        if any(word in href.lower() for word in bad_words):
            continue

        car_urls.add(BASE_URL + href)

    return sorted(car_urls)

In [19]:
all_car_urls = []

for brand in brand_urls:

    print(f"Scraping : {brand}")

    try:
        urls = get_car_urls(brand)
        all_car_urls.extend(urls)

    except Exception as e:
        print(e)

    time.sleep(random.uniform(1,2))

all_car_urls = sorted(set(all_car_urls))

print("Total Cars :",len(all_car_urls))

Scraping : https://www.carwale.com/aston-martin-cars/
Scraping : https://www.carwale.com/audi-cars/
Scraping : https://www.carwale.com/bentley-cars/
Scraping : https://www.carwale.com/bmw-cars/
Scraping : https://www.carwale.com/byd-cars/
Scraping : https://www.carwale.com/citroen-cars/
Scraping : https://www.carwale.com/compare-cars/
Scraping : https://www.carwale.com/ferrari-cars/
Scraping : https://www.carwale.com/force-motors-cars/
Scraping : https://www.carwale.com/honda-cars/
Scraping : https://www.carwale.com/hyundai-cars/
Scraping : https://www.carwale.com/isuzu-cars/
Scraping : https://www.carwale.com/jaguar-cars/
Scraping : https://www.carwale.com/jeep-cars/
Scraping : https://www.carwale.com/kia-cars/
Scraping : https://www.carwale.com/lamborghini-cars/
Scraping : https://www.carwale.com/land-rover-cars/
Scraping : https://www.carwale.com/lexus-cars/
Scraping : https://www.carwale.com/lotus-cars/
Scraping : https://www.carwale.com/mahindra-cars/
Scraping : https://www.carwale.com/maruti-suzuki-cars/
Scraping : https://www.carwale.com/maserati-cars/
Scraping : https://www.carwale.com/mclaren-cars/
Scraping : https://www.carwale.com/mercedes-benz-cars/
Scraping : https://www.carwale.com/mg-cars/
Scraping : https://www.carwale.com/mini-cars/
Scraping : https://www.carwale.com/nissan-cars/
Scraping : https://www.carwale.com/porsche-cars/
Scraping : https://www.carwale.com/renault-cars/
Scraping : https://www.carwale.com/rolls-royce-cars/
Scraping : https://www.carwale.com/skoda-cars/
Scraping : https://www.carwale.com/tata-cars/
Scraping : https://www.carwale.com/tesla-cars/
Scraping : https://www.carwale.com/toyota-cars/
Scraping : https://www.carwale.com/upcoming-cars/
Scraping : https://www.carwale.com/vinfast-cars/
Scraping : https://www.carwale.com/volkswagen-cars/
Scraping : https://www.carwale.com/volvo-cars/
Total Cars : 682

In [21]:
def scrape_car(url):

    response = requests.get(url, headers=HEADERS)

    if response.status_code != 200:
        return None

    soup = BeautifulSoup(response.text, "html.parser")

    ld_json = None

    for script in soup.find_all("script", type="application/ld+json"):

        try:
            data = json.loads(script.string)

            if "@graph" in data:

                for item in data["@graph"]:

                    if item.get("@type") == "Car":
                        ld_json = item
                        break

        except:
            continue

    if ld_json is None:
        return None

    # -----------------------
    # Price
    # -----------------------

    price = np.nan

    if "offers" in ld_json:

        offer = ld_json["offers"]

        if isinstance(offer, dict):
            price = offer.get("price", np.nan)

    # -----------------------
    # Brand
    # -----------------------

    brand = np.nan

    if "brand" in ld_json:

        if isinstance(ld_json["brand"], dict):
            brand = ld_json["brand"].get("name", np.nan)

        else:
            brand = ld_json["brand"]

    # -----------------------
    # Description
    # -----------------------

    description = ld_json.get("description", "")

    fuel = np.nan
    transmission = np.nan
    engine = np.nan
    mileage = np.nan
    seating = np.nan

    fuel_match = re.search(
        r"(Petrol|Diesel|CNG|Electric|Hybrid)",
        description,
        re.I
    )

    if fuel_match:
        fuel = fuel_match.group(1).title()

    transmission_match = re.search(
        r"(Manual|Automatic)",
        description,
        re.I
    )

    if transmission_match:
        transmission = transmission_match.group(1).title()

    engine_match = re.search(
        r"(\d{3,4})\s*to\s*(\d{3,4})\s*cc",
        description,
        re.I
    )

    if engine_match:

        engine = engine_match.group(1)

    else:

        engine_match = re.search(
            r"(\d{3,4})\s*cc",
            description,
            re.I
        )

        if engine_match:
            engine = engine_match.group(1)

    mileage_match = re.search(
        r"mileage of\s*([\d\.]+)",
        description,
        re.I
    )

    if mileage_match:
        mileage = mileage_match.group(1)

    seat_match = re.search(
        r"(\d)\s*seater",
        description,
        re.I
    )

    if seat_match:
        seating = seat_match.group(1)

    rating = np.nan

    if "aggregateRating" in ld_json:

        rating = ld_json["aggregateRating"].get(
            "ratingValue",
            np.nan
        )

    return {

        "Car Name": ld_json.get("name", np.nan),
        "Brand": brand,
        "Price": price,
        "Fuel Type": fuel,
        "Transmission": transmission,
        "Engine (cc)": engine,
        "Mileage": mileage,
        "Seating Capacity": seating,
        "User Rating": rating,
        "URL": url

    }

In [23]:
all_cars = []

for i, url in enumerate(all_car_urls, start=1):

    print(f"{i}/{len(all_car_urls)} : {url}")

    try:

        car_data = scrape_car(url)

        if car_data:
            all_cars.append(car_data)

    except Exception as e:

        print(f"Error : {e}")

    time.sleep(random.uniform(1,2))

1/682 : https://www.carwale.com/aston-martin-cars/db11/
2/682 : https://www.carwale.com/aston-martin-cars/db12/
3/682 : https://www.carwale.com/aston-martin-cars/db9/
4/682 : https://www.carwale.com/aston-martin-cars/dbx/
5/682 : https://www.carwale.com/aston-martin-cars/rapide/
6/682 : https://www.carwale.com/aston-martin-cars/vanquish/
7/682 : https://www.carwale.com/aston-martin-cars/vantage/
8/682 : https://www.carwale.com/aston-martin-cars/virage/
9/682 : https://www.carwale.com/audi-cars/a4/
10/682 : https://www.carwale.com/audi-cars/a5-cabriolet/
11/682 : https://www.carwale.com/audi-cars/a5/
12/682 : https://www.carwale.com/audi-cars/a6/
13/682 : https://www.carwale.com/audi-cars/a8-l/
14/682 : https://www.carwale.com/audi-cars/e-tron-gt/
15/682 : https://www.carwale.com/audi-cars/e-tron-sportback/
16/682 : https://www.carwale.com/audi-cars/e-tron/
17/682 : https://www.carwale.com/audi-cars/new-a3/
18/682 : https://www.carwale.com/audi-cars/new-q3/
19/682 : https://www.carwale.com/audi-cars/new-q5-third-gen/
20/682 : https://www.carwale.com/audi-cars/q2/
21/682 : https://www.carwale.com/audi-cars/q3-sportback/
22/682 : https://www.carwale.com/audi-cars/q3/
23/682 : https://www.carwale.com/audi-cars/q5/
24/682 : https://www.carwale.com/audi-cars/q6-e-tron/
25/682 : https://www.carwale.com/audi-cars/q7/
26/682 : https://www.carwale.com/audi-cars/q8-e-tron/
27/682 : https://www.carwale.com/audi-cars/q8-sportback-e-tron/
28/682 : https://www.carwale.com/audi-cars/q8/
29/682 : https://www.carwale.com/audi-cars/q9/
30/682 : https://www.carwale.com/audi-cars/r8/
31/682 : https://www.carwale.com/audi-cars/rs-q8-performance/
32/682 : https://www.carwale.com/audi-cars/rs5/
33/682 : https://www.carwale.com/audi-cars/rs7-sportback/
34/682 : https://www.carwale.com/audi-cars/s5-sportback/
35/682 : https://www.carwale.com/audi-cars/s6/
36/682 : https://www.carwale.com/audi-cars/sq8/
37/682 : https://www.carwale.com/audi-cars/tt/
38/682 : https://www.carwale.com/bentley-cars/arnage/
39/682 : https://www.carwale.com/bentley-cars/azure/
40/682 : https://www.carwale.com/bentley-cars/bentayga/
41/682 : https://www.carwale.com/bentley-cars/continentalgtc/
42/682 : https://www.carwale.com/bentley-cars/continentalsupersports/
43/682 : https://www.carwale.com/bentley-cars/mulsanne/
44/682 : https://www.carwale.com/bmw-cars/1-series/
45/682 : https://www.carwale.com/bmw-cars/2-series-gran-coupe/
46/682 : https://www.carwale.com/bmw-cars/3-series-gran-limousine/
47/682 : https://www.carwale.com/bmw-cars/3-series/
48/682 : https://www.carwale.com/bmw-cars/5-series/
49/682 : https://www.carwale.com/bmw-cars/6-series-gran-coupe/
50/682 : https://www.carwale.com/bmw-cars/6-series-gt/
51/682 : https://www.carwale.com/bmw-cars/7-series/
52/682 : https://www.carwale.com/bmw-cars/8-series/
53/682 : https://www.carwale.com/bmw-cars/i4/
54/682 : https://www.carwale.com/bmw-cars/i5/
55/682 : https://www.carwale.com/bmw-cars/i7/
56/682 : https://www.carwale.com/bmw-cars/ix/
57/682 : https://www.carwale.com/bmw-cars/ix1-lwb/
58/682 : https://www.carwale.com/bmw-cars/ix1/
59/682 : https://www.carwale.com/bmw-cars/ix3/
60/682 : https://www.carwale.com/bmw-cars/m2/
61/682 : https://www.carwale.com/bmw-cars/m3/
62/682 : https://www.carwale.com/bmw-cars/m340i/
63/682 : https://www.carwale.com/bmw-cars/m4-cs/
64/682 : https://www.carwale.com/bmw-cars/m4/
65/682 : https://www.carwale.com/bmw-cars/m440i/
66/682 : https://www.carwale.com/bmw-cars/m5/
67/682 : https://www.carwale.com/bmw-cars/m6/
68/682 : https://www.carwale.com/bmw-cars/m8/
69/682 : https://www.carwale.com/bmw-cars/new-x5/
70/682 : https://www.carwale.com/bmw-cars/x1/
71/682 : https://www.carwale.com/bmw-cars/x3-m/
72/682 : https://www.carwale.com/bmw-cars/x3-m40i/
73/682 : https://www.carwale.com/bmw-cars/x3/
74/682 : https://www.carwale.com/bmw-cars/x4/
75/682 : https://www.carwale.com/bmw-cars/x5-m/
76/682 : https://www.carwale.com/bmw-cars/x5/
77/682 : https://www.carwale.com/bmw-cars/x6/
78/682 : https://www.carwale.com/bmw-cars/x7/
79/682 : https://www.carwale.com/bmw-cars/x8/
80/682 : https://www.carwale.com/bmw-cars/xm/
81/682 : https://www.carwale.com/bmw-cars/z3/
82/682 : https://www.carwale.com/bmw-cars/z4/
83/682 : https://www.carwale.com/byd-cars/atto-2/
84/682 : https://www.carwale.com/byd-cars/atto-3-facelift/
85/682 : https://www.carwale.com/byd-cars/atto-3/
86/682 : https://www.carwale.com/byd-cars/e6/
87/682 : https://www.carwale.com/byd-cars/emax-7/
88/682 : https://www.carwale.com/byd-cars/seal-u-dm-i/
89/682 : https://www.carwale.com/byd-cars/seal/
90/682 : https://www.carwale.com/byd-cars/sealion-7/
91/682 : https://www.carwale.com/citroen-cars/aircross-x-facelift/
92/682 : https://www.carwale.com/citroen-cars/aircross-x/
93/682 : https://www.carwale.com/citroen-cars/basalt-ev/
94/682 : https://www.carwale.com/citroen-cars/basalt-x/
95/682 : https://www.carwale.com/citroen-cars/basalt/
96/682 : https://www.carwale.com/citroen-cars/c3-facelift/
97/682 : https://www.carwale.com/citroen-cars/c3-x/
98/682 : https://www.carwale.com/citroen-cars/c5-aircross/
99/682 : https://www.carwale.com/citroen-cars/ec3-x/
100/682 : https://www.carwale.com/citroen-cars/new-c5-aircross/
101/682 : https://www.carwale.com/citroen-cars/sub-4-metre-compact-suv/
102/682 : https://www.carwale.com/compare-cars/hyundai-exter-vs-tata-punch/
103/682 : https://www.carwale.com/compare-cars/hyundai-venue-vs-kia-sonet/
104/682 : https://www.carwale.com/compare-cars/kia-seltos-vs-hyundai-creta/
105/682 : https://www.carwale.com/compare-cars/mahindra-thar-roxx-vs-mahindra-scorpio-n/
106/682 : https://www.carwale.com/compare-cars/mahindra-thar-vs-mahindra-thar-roxx/
107/682 : https://www.carwale.com/compare-cars/mahindra-xuv-3xo-vs-tata-nexon/
108/682 : https://www.carwale.com/compare-cars/mahindra-xuv-7xo-vs-mahindra-scorpio-n/
109/682 : https://www.carwale.com/compare-cars/maruti-suzuki-fronx-vs-maruti-suzuki-baleno/
110/682 : https://www.carwale.com/compare-cars/nissan-tekton-vs-renault-duster/
111/682 : https://www.carwale.com/compare-cars/tata-harrier-ev-vs-tata-sierra-ev/
112/682 : https://www.carwale.com/compare-cars/tata-sierra-vs-hyundai-creta/
113/682 : https://www.carwale.com/compare-cars/tata-sierra-vs-kia-seltos/
114/682 : https://www.carwale.com/compare-cars/toyota-hyryder-vs-maruti-suzuki-grand-vitara/
115/682 : https://www.carwale.com/ferrari-cars/296-gtb/
116/682 : https://www.carwale.com/ferrari-cars/296-gts/
117/682 : https://www.carwale.com/ferrari-cars/360/
118/682 : https://www.carwale.com/ferrari-cars/458/
119/682 : https://www.carwale.com/ferrari-cars/488/
120/682 : https://www.carwale.com/ferrari-cars/575superamerica/
121/682 : https://www.carwale.com/ferrari-cars/599gtbfiorano/
122/682 : https://www.carwale.com/ferrari-cars/612/
123/682 : https://www.carwale.com/ferrari-cars/812/
124/682 : https://www.carwale.com/ferrari-cars/849-testarossa/
125/682 : https://www.carwale.com/ferrari-cars/amalfi-spider/
126/682 : https://www.carwale.com/ferrari-cars/california/
127/682 : https://www.carwale.com/ferrari-cars/f12berlinetta/
128/682 : https://www.carwale.com/ferrari-cars/f430/
129/682 : https://www.carwale.com/ferrari-cars/f8-tributo/
130/682 : https://www.carwale.com/ferrari-cars/ff/
131/682 : https://www.carwale.com/ferrari-cars/gtc4-lusso/
132/682 : https://www.carwale.com/ferrari-cars/portofino/
133/682 : https://www.carwale.com/ferrari-cars/purosangue-suv/
134/682 : https://www.carwale.com/ferrari-cars/roma/
135/682 : https://www.carwale.com/force-motors-cars/forceone/
136/682 : https://www.carwale.com/force-motors-cars/gurkha/
137/682 : https://www.carwale.com/force-motors-cars/trax-cruiser/
138/682 : https://www.carwale.com/honda-cars/0-alpha/
139/682 : https://www.carwale.com/honda-cars/accord/
140/682 : https://www.carwale.com/honda-cars/amaze-2nd-gen/
141/682 : https://www.carwale.com/honda-cars/amaze/
142/682 : https://www.carwale.com/honda-cars/br-v/
143/682 : https://www.carwale.com/honda-cars/brio/
144/682 : https://www.carwale.com/honda-cars/city-hybrid-ehev/
145/682 : https://www.carwale.com/honda-cars/city/
146/682 : https://www.carwale.com/honda-cars/civic/
147/682 : https://www.carwale.com/honda-cars/compact-suv/
148/682 : https://www.carwale.com/honda-cars/concerto/
149/682 : https://www.carwale.com/honda-cars/cr-v-hybrid/
150/682 : https://www.carwale.com/honda-cars/cr-v/
151/682 : https://www.carwale.com/honda-cars/crx/
152/682 : https://www.carwale.com/honda-cars/elevate-based-three-row-suv/
153/682 : https://www.carwale.com/honda-cars/elevate-ev/
154/682 : https://www.carwale.com/honda-cars/elevate-facelift/
155/682 : https://www.carwale.com/honda-cars/elevate/
156/682 : https://www.carwale.com/honda-cars/jazz/
157/682 : https://www.carwale.com/honda-cars/mobilio/
158/682 : https://www.carwale.com/honda-cars/prelude/
159/682 : https://www.carwale.com/honda-cars/stepwgn/
160/682 : https://www.carwale.com/honda-cars/super-one/
161/682 : https://www.carwale.com/honda-cars/wr-v/
162/682 : https://www.carwale.com/honda-cars/zr-v/
163/682 : https://www.carwale.com/hyundai-cars/accent/
164/682 : https://www.carwale.com/hyundai-cars/alcazar/
165/682 : https://www.carwale.com/hyundai-cars/aura/
166/682 : https://www.carwale.com/hyundai-cars/bayon/
167/682 : https://www.carwale.com/hyundai-cars/boulder/
168/682 : https://www.carwale.com/hyundai-cars/casper/
169/682 : https://www.carwale.com/hyundai-cars/creta-electric/
170/682 : https://www.carwale.com/hyundai-cars/creta-facelift/
171/682 : https://www.carwale.com/hyundai-cars/creta-n-line/
172/682 : https://www.carwale.com/hyundai-cars/creta/
173/682 : https://www.carwale.com/hyundai-cars/elantra/
174/682 : https://www.carwale.com/hyundai-cars/eon/
175/682 : https://www.carwale.com/hyundai-cars/exter/
176/682 : https://www.carwale.com/hyundai-cars/genesis/
177/682 : https://www.carwale.com/hyundai-cars/grand-i10-nios/
178/682 : https://www.carwale.com/hyundai-cars/grand-i10/
179/682 : https://www.carwale.com/hyundai-cars/i20-active/
180/682 : https://www.carwale.com/hyundai-cars/i20-n-line/
181/682 : https://www.carwale.com/hyundai-cars/i20/
182/682 : https://www.carwale.com/hyundai-cars/ioniq-5/
183/682 : https://www.carwale.com/hyundai-cars/ioniq-6/
184/682 : https://www.carwale.com/hyundai-cars/ioniq-9/
185/682 : https://www.carwale.com/hyundai-cars/mid-size-suv/
186/682 : https://www.carwale.com/hyundai-cars/new-i20/
187/682 : https://www.carwale.com/hyundai-cars/new-kona/
188/682 : https://www.carwale.com/hyundai-cars/new-santa-fe/
189/682 : https://www.carwale.com/hyundai-cars/palisade/
190/682 : https://www.carwale.com/hyundai-cars/santro/
191/682 : https://www.carwale.com/hyundai-cars/sonata/
192/682 : https://www.carwale.com/hyundai-cars/stargazer/
193/682 : https://www.carwale.com/hyundai-cars/staria/
194/682 : https://www.carwale.com/hyundai-cars/sub-compact-ev-suv/
195/682 : https://www.carwale.com/hyundai-cars/terracan20032006/
196/682 : https://www.carwale.com/hyundai-cars/tucson-facelift/
197/682 : https://www.carwale.com/hyundai-cars/tucson/
198/682 : https://www.carwale.com/hyundai-cars/venue-n-line/
199/682 : https://www.carwale.com/hyundai-cars/venue/
200/682 : https://www.carwale.com/hyundai-cars/verna/
201/682 : https://www.carwale.com/hyundai-cars/xcent/
202/682 : https://www.carwale.com/isuzu-cars/hi-lander/
203/682 : https://www.carwale.com/isuzu-cars/mu-x/
204/682 : https://www.carwale.com/isuzu-cars/trooper/
205/682 : https://www.carwale.com/isuzu-cars/v-cross/
206/682 : https://www.carwale.com/jaguar-cars/e-pace/
207/682 : https://www.carwale.com/jaguar-cars/f-pace/
208/682 : https://www.carwale.com/jaguar-cars/f-type/
209/682 : https://www.carwale.com/jaguar-cars/i-pace/
210/682 : https://www.carwale.com/jaguar-cars/type-00/
211/682 : https://www.carwale.com/jaguar-cars/xe/
212/682 : https://www.carwale.com/jaguar-cars/xf/
213/682 : https://www.carwale.com/jaguar-cars/xj-l/
214/682 : https://www.carwale.com/jaguar-cars/xj50/
215/682 : https://www.carwale.com/jaguar-cars/xk/
216/682 : https://www.carwale.com/jeep-cars/avenger/
217/682 : https://www.carwale.com/jeep-cars/compass/
218/682 : https://www.carwale.com/jeep-cars/grand-cherokee/
219/682 : https://www.carwale.com/jeep-cars/kaiser/
220/682 : https://www.carwale.com/jeep-cars/meridian/
221/682 : https://www.carwale.com/jeep-cars/renegade/
222/682 : https://www.carwale.com/jeep-cars/willys/
223/682 : https://www.carwale.com/jeep-cars/wrangler/
224/682 : https://www.carwale.com/kia-cars/carens-clavis-ev/
225/682 : https://www.carwale.com/kia-cars/carens-clavis/
226/682 : https://www.carwale.com/kia-cars/carens/
227/682 : https://www.carwale.com/kia-cars/carnival/
228/682 : https://www.carwale.com/kia-cars/ev3/
229/682 : https://www.carwale.com/kia-cars/ev5/
230/682 : https://www.carwale.com/kia-cars/ev6/
231/682 : https://www.carwale.com/kia-cars/ev9/
232/682 : https://www.carwale.com/kia-cars/new-sonet/
233/682 : https://www.carwale.com/kia-cars/rio/
234/682 : https://www.carwale.com/kia-cars/seltos/
235/682 : https://www.carwale.com/kia-cars/sonet/
236/682 : https://www.carwale.com/kia-cars/sorento-hybrid/
237/682 : https://www.carwale.com/kia-cars/syros-ev/
238/682 : https://www.carwale.com/kia-cars/syros/
239/682 : https://www.carwale.com/kia-cars/tasman/
240/682 : https://www.carwale.com/lamborghini-cars/aventador-ultimae/
241/682 : https://www.carwale.com/lamborghini-cars/huracan-evo-spyder/
242/682 : https://www.carwale.com/lamborghini-cars/huracan-sterrato/
243/682 : https://www.carwale.com/lamborghini-cars/huracan-sto/
244/682 : https://www.carwale.com/lamborghini-cars/huracan-tecnica/
245/682 : https://www.carwale.com/lamborghini-cars/murcielago/
246/682 : https://www.carwale.com/lamborghini-cars/revuelto/
247/682 : https://www.carwale.com/lamborghini-cars/temerario/
248/682 : https://www.carwale.com/lamborghini-cars/urus-performante/
249/682 : https://www.carwale.com/lamborghini-cars/urus-s/
250/682 : https://www.carwale.com/lamborghini-cars/urus-se/
251/682 : https://www.carwale.com/land-rover-cars/defender-facelift/
252/682 : https://www.carwale.com/land-rover-cars/defender/
253/682 : https://www.carwale.com/land-rover-cars/discovery-sport/
254/682 : https://www.carwale.com/land-rover-cars/discovery/
255/682 : https://www.carwale.com/land-rover-cars/freelander-2/
256/682 : https://www.carwale.com/land-rover-cars/range-rover-evoque/
257/682 : https://www.carwale.com/land-rover-cars/range-rover-sport/
258/682 : https://www.carwale.com/land-rover-cars/range-rover-velar/
259/682 : https://www.carwale.com/land-rover-cars/range-rover/
260/682 : https://www.carwale.com/lexus-cars/es-350h/
261/682 : https://www.carwale.com/lexus-cars/es/
262/682 : https://www.carwale.com/lexus-cars/gs350/
263/682 : https://www.carwale.com/lexus-cars/lc-500h/
264/682 : https://www.carwale.com/lexus-cars/lm/
265/682 : https://www.carwale.com/lexus-cars/ls/
266/682 : https://www.carwale.com/lexus-cars/lx/
267/682 : https://www.carwale.com/lexus-cars/nx/
268/682 : https://www.carwale.com/lexus-cars/rx/
269/682 : https://www.carwale.com/lexus-cars/sc430/
270/682 : https://www.carwale.com/lexus-cars/ux-300e/
271/682 : https://www.carwale.com/lotus-cars/eletre/
272/682 : https://www.carwale.com/lotus-cars/emeya/
273/682 : https://www.carwale.com/lotus-cars/emira/
274/682 : https://www.carwale.com/mahindra-cars/alturas-g4/
275/682 : https://www.carwale.com/mahindra-cars/armada/
276/682 : https://www.carwale.com/mahindra-cars/be-6-fe/
277/682 : https://www.carwale.com/mahindra-cars/be-6/
278/682 : https://www.carwale.com/mahindra-cars/be07/
279/682 : https://www.carwale.com/mahindra-cars/be09/
280/682 : https://www.carwale.com/mahindra-cars/bolero-2026/
281/682 : https://www.carwale.com/mahindra-cars/bolero-neo-plus/
282/682 : https://www.carwale.com/mahindra-cars/bolero-neo/
283/682 : https://www.carwale.com/mahindra-cars/bolero/
284/682 : https://www.carwale.com/mahindra-cars/e2o-plus/
285/682 : https://www.carwale.com/mahindra-cars/ekuv100/
286/682 : https://www.carwale.com/mahindra-cars/global-pik-up/
287/682 : https://www.carwale.com/mahindra-cars/jeep/
288/682 : https://www.carwale.com/mahindra-cars/kuv100-nxt/
289/682 : https://www.carwale.com/mahindra-cars/marazzo/
290/682 : https://www.carwale.com/mahindra-cars/marshal/
291/682 : https://www.carwale.com/mahindra-cars/nuvosport/
292/682 : https://www.carwale.com/mahindra-cars/revai/
293/682 : https://www.carwale.com/mahindra-cars/scorpio-facelift/
294/682 : https://www.carwale.com/mahindra-cars/scorpio-n-facelift/
295/682 : https://www.carwale.com/mahindra-cars/scorpio-n/
296/682 : https://www.carwale.com/mahindra-cars/scorpio/
297/682 : https://www.carwale.com/mahindra-cars/thar-electric/
298/682 : https://www.carwale.com/mahindra-cars/thar-facelift/
299/682 : https://www.carwale.com/mahindra-cars/thar-roxx/
300/682 : https://www.carwale.com/mahindra-cars/thar/
301/682 : https://www.carwale.com/mahindra-cars/tuv300/
302/682 : https://www.carwale.com/mahindra-cars/veritovibecs/
303/682 : https://www.carwale.com/mahindra-cars/vision-s-compact-suv/
304/682 : https://www.carwale.com/mahindra-cars/vision-s-sub-compact-suv/
305/682 : https://www.carwale.com/mahindra-cars/vision-sxt/
306/682 : https://www.carwale.com/mahindra-cars/vision-t/
307/682 : https://www.carwale.com/mahindra-cars/vision-x-compact-suv/
308/682 : https://www.carwale.com/mahindra-cars/vision-x-sub-compact-suv/
309/682 : https://www.carwale.com/mahindra-cars/voyager/
310/682 : https://www.carwale.com/mahindra-cars/xev-7e/
311/682 : https://www.carwale.com/mahindra-cars/xev-9e/
312/682 : https://www.carwale.com/mahindra-cars/xev-9s/
313/682 : https://www.carwale.com/mahindra-cars/xuv-3xo-ev/
314/682 : https://www.carwale.com/mahindra-cars/xuv-3xo/
315/682 : https://www.carwale.com/mahindra-cars/xuv-7xo/
316/682 : https://www.carwale.com/mahindra-cars/xuv300-turbosport/
317/682 : https://www.carwale.com/mahindra-cars/xuv400/
318/682 : https://www.carwale.com/mahindra-cars/xuv500/
319/682 : https://www.carwale.com/mahindra-cars/xylo/
320/682 : https://www.carwale.com/maruti-suzuki-cars/1000-1990-2000/
321/682 : https://www.carwale.com/maruti-suzuki-cars/a-star/
322/682 : https://www.carwale.com/maruti-suzuki-cars/alto-800/
323/682 : https://www.carwale.com/maruti-suzuki-cars/alto-k10/
324/682 : https://www.carwale.com/maruti-suzuki-cars/baleno-1999-2007/
325/682 : https://www.carwale.com/maruti-suzuki-cars/baleno-facelift/
326/682 : https://www.carwale.com/maruti-suzuki-cars/baleno/
327/682 : https://www.carwale.com/maruti-suzuki-cars/brezza-2026/
328/682 : https://www.carwale.com/maruti-suzuki-cars/brezza/
329/682 : https://www.carwale.com/maruti-suzuki-cars/celerio-x/
330/682 : https://www.carwale.com/maruti-suzuki-cars/celerio/
331/682 : https://www.carwale.com/maruti-suzuki-cars/ciaz/
332/682 : https://www.carwale.com/maruti-suzuki-cars/dzire/
333/682 : https://www.carwale.com/maruti-suzuki-cars/e-vitara/
334/682 : https://www.carwale.com/maruti-suzuki-cars/eeco/
335/682 : https://www.carwale.com/maruti-suzuki-cars/ertiga/
336/682 : https://www.carwale.com/maruti-suzuki-cars/esteem/
337/682 : https://www.carwale.com/maruti-suzuki-cars/estilo/
338/682 : https://www.carwale.com/maruti-suzuki-cars/fronx-facelift/
339/682 : https://www.carwale.com/maruti-suzuki-cars/fronx-flex-fuel/
340/682 : https://www.carwale.com/maruti-suzuki-cars/fronx/
341/682 : https://www.carwale.com/maruti-suzuki-cars/futuro-e/
342/682 : https://www.carwale.com/maruti-suzuki-cars/grand-vitara/
343/682 : https://www.carwale.com/maruti-suzuki-cars/gypsy/
344/682 : https://www.carwale.com/maruti-suzuki-cars/ignis/
345/682 : https://www.carwale.com/maruti-suzuki-cars/invicto/
346/682 : https://www.carwale.com/maruti-suzuki-cars/jimny/
347/682 : https://www.carwale.com/maruti-suzuki-cars/kizashi/
348/682 : https://www.carwale.com/maruti-suzuki-cars/new-ertiga/
349/682 : https://www.carwale.com/maruti-suzuki-cars/omni/

In [25]:
raw_df = pd.DataFrame(all_cars)

print(raw_df.shape)

raw_df.head()

(514, 10)

,Car Name,Brand,Price,Fuel Type,Transmission,Engine (cc),Mileage,Seating Capacity,User Rating,URL
0,Aston Martin DB11,Aston Martin,31121622.0,NaN,Automatic,5198,8.9,4,4.5,https://www.carwale.com/aston-martin-cars/db11/
1,Aston Martin DB12,Aston Martin,43418919.0,NaN,Automatic,5198,12.75,4,4.1,https://www.carwale.com/aston-martin-cars/db12/
2,Aston Martin DBX,Aston Martin,38200000.0,NaN,Automatic,3982,10.1,5,4.7,https://www.carwale.com/aston-martin-cars/dbx/
3,Aston Martin Vanquish,Aston Martin,83716216.0,NaN,Automatic,5203,NaN,2,4.9,https://www.carwale.com/aston-martin-cars/vanq...
4,Aston Martin Vantage,Aston Martin,37743243.0,NaN,Automatic,3982,NaN,2,5.0,https://www.carwale.com/aston-martin-cars/vant...

In [27]:
print(f"Total URLs Collected : {len(all_car_urls)}")
print(f"Successfully Scraped : {len(all_cars)}")

raw_df.info()

raw_df.isnull().sum()

Total URLs Collected : 682
Successfully Scraped : 514
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 514 entries, 0 to 513
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Car Name          514 non-null    object
 1   Brand             514 non-null    object
 2   Price             514 non-null    float64
 3   Fuel Type         4 non-null      object
 4   Transmission      401 non-null    object
 5   Engine (cc)       320 non-null    object
 6   Mileage           144 non-null    object
 7   Seating Capacity  362 non-null    object
 8   User Rating       393 non-null    float64
 9   URL               514 non-null    object
dtypes: float64(2), object(8)
memory usage: 40.3+ KB

Car Name              0
Brand                 0
Price                 0
Fuel Type           510
Transmission        113
Engine (cc)         194
Mileage             370
Seating Capacity    152
User Rating         121
URL                   0
dtype: int64

In [31]:
raw_df.to_csv(
    "carwale_raw.csv",
    index=False
)

print("carwale_raw.csv has been saved successfully!")

carwale_raw.csv has been saved successfully!

In [33]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 514 entries, 0 to 513
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Car Name          514 non-null    object
 1   Brand             514 non-null    object
 2   Price             514 non-null    float64
 3   Fuel Type         4 non-null      object
 4   Transmission      401 non-null    object
 5   Engine (cc)       320 non-null    object
 6   Mileage           144 non-null    object
 7   Seating Capacity  362 non-null    object
 8   User Rating       393 non-null    float64
 9   URL               514 non-null    object
dtypes: float64(2), object(8)
memory usage: 40.3+ KB

In [35]:
raw_df.isnull().sum()

Car Name              0
Brand                 0
Price                 0
Fuel Type           510
Transmission        113
Engine (cc)         194
Mileage             370
Seating Capacity    152
User Rating         121
URL                   0
dtype: int64

In [37]:
raw_df.duplicated().sum()

0

In [39]:
raw_df.head()

,Car Name,Brand,Price,Fuel Type,Transmission,Engine (cc),Mileage,Seating Capacity,User Rating,URL
0,Aston Martin DB11,Aston Martin,31121622.0,NaN,Automatic,5198,8.9,4,4.5,https://www.carwale.com/aston-martin-cars/db11/
1,Aston Martin DB12,Aston Martin,43418919.0,NaN,Automatic,5198,12.75,4,4.1,https://www.carwale.com/aston-martin-cars/db12/
2,Aston Martin DBX,Aston Martin,38200000.0,NaN,Automatic,3982,10.1,5,4.7,https://www.carwale.com/aston-martin-cars/dbx/
3,Aston Martin Vanquish,Aston Martin,83716216.0,NaN,Automatic,5203,NaN,2,4.9,https://www.carwale.com/aston-martin-cars/vanq...
4,Aston Martin Vantage,Aston Martin,37743243.0,NaN,Automatic,3982,NaN,2,5.0,https://www.carwale.com/aston-martin-cars/vant...

In [41]:
fuel_brand_map = {}

print("Collecting model URLs...")

for brand_url in brand_urls:

    brand_slug = brand_url.split("/")[-2].replace("-cars", "").lower()
    brand_name = brand_slug.capitalize()

    fuel_brand_map[brand_name] = []

    try:

        response = requests.get(brand_url, headers=HEADERS)

        if response.status_code != 200:
            continue

        soup = BeautifulSoup(response.text, "lxml")

        seen_urls = set()

        for tag in soup.find_all("a", href=True):

            href = tag.get("href", "").strip()

            full_url = urljoin(BASE_URL, href)

            if f"/{brand_slug}-cars/" not in href.lower():
                continue

            if re.search(r"\d{4}-\d{4}", href):
                continue

            noise_keywords = [
                "compare",
                "upcoming",
                "old-generation",
                "used",
                "history",
                "discontinued",
                "price-in-",
                "images",
                "colors",
                "videos",
                "expert-reviews",
                "reviews",
                "news",
                "features"
            ]

            if any(word in href.lower() for word in noise_keywords):
                continue

            if href.lower().rstrip("/") == f"/{brand_slug}-cars":
                continue

            if full_url not in seen_urls:
                seen_urls.add(full_url)
                fuel_brand_map[brand_name].append(full_url)

        print(f"{brand_name} : {len(fuel_brand_map[brand_name])} models")

        time.sleep(random.uniform(1,2))

    except Exception as e:
        print(e)

Collecting model URLs...
Aston-martin : 15 models
Audi : 36 models
Bentley : 8 models
Bmw : 45 models
Byd : 11 models
Citroen : 19 models
Compare : 0 models
Ferrari : 26 models
Force-motors : 6 models
Honda : 30 models
Hyundai : 48 models
Isuzu : 8 models
Jaguar : 13 models
Jeep : 18 models
Kia : 18 models
Lamborghini : 15 models
Land-rover : 15 models
Lexus : 17 models
Lotus : 6 models
Mahindra : 56 models
Maruti-suzuki : 62 models
Maserati : 14 models
Mclaren : 8 models
Mercedes-benz : 75 models
Mg : 31 models
Mini : 16 models
Nissan : 34 models
Porsche : 17 models
Renault : 15 models
Rolls-royce : 13 models
Skoda : 33 models
Tata : 56 models
Tesla : 6 models
Toyota : 59 models
Upcoming : 0 models
Vinfast : 10 models
Volkswagen : 30 models
Volvo : 18 models

In [43]:
def scrape_fuel_specs(car_url, brand_name):

    response = requests.get(car_url, headers=HEADERS)

    if response.status_code != 200:
        return []

    soup = BeautifulSoup(response.text, "lxml")

    title = soup.find("h1")

    car_name = (
        title.text.replace(brand_name, "").strip()
        if title else "Unknown"
    )

    rating = "Not Rated"

    rating_element = soup.find(
        "p",
        class_=re.compile(r"o-iY.*o-jq")
    )

    if rating_element:

        rating = rating_element.text.strip()

        if "/5" not in rating:
            rating += "/5"

    variant_blocks = (
        soup.find_all("div", data_version_id=True)
        or
        soup.find_all(
            "div",
            class_=re.compile(r"sc-jq0284")
        )
    )

    if not variant_blocks:
        variant_blocks = soup.find_all("div")

    records = []

    for block in variant_blocks:

        block_text = block.get_text(" | ")

        if "Rs." not in block_text:
            continue

        if not any(
            fuel in block_text
            for fuel in ["Petrol","Diesel","CNG","Electric"]
        ):
            continue

        price_match = re.search(
            r"Rs\.\s*\d+(?:\.\d+)?\s*(?:Lakh|Crore)",
            block_text
        )

        price = (
            price_match.group(0)
            if price_match
            else "On Request"
        )

        fuel = "Unknown"

        if "Petrol" in block_text:
            fuel = "Petrol"
        elif "Diesel" in block_text:
            fuel = "Diesel"
        elif "CNG" in block_text:
            fuel = "CNG"
        elif "Electric" in block_text:
            fuel = "Electric"

        transmission = "Unknown"

        if "Manual" in block_text:
            transmission = "Manual"

        elif any(
            t in block_text
            for t in [
                "Automatic",
                "AMT",
                "CVT",
                "DCT",
                "Torque Converter"
            ]
        ):
            transmission = "Automatic"

        engine = "Unknown"

        engine_match = re.search(
            r"(\d+\.\d+L(?::\s*Turbo)?|\d+\s*cc|\d+\s*kWh)",
            block_text
        )

        if engine_match:
            engine = engine_match.group(0)

        elif fuel == "Electric":
            engine = "Electric Motor"

        mileage = "N/A"

        mileage_match = re.search(
            r"(\d+(?:\.\d+)?\s*(?:kmpl|km/kg|km/charge))",
            block_text
        )

        if mileage_match:
            mileage = mileage_match.group(0)

        records.append({

            "Car Name": car_name,
            "Brand": brand_name,
            "Price": price,
            "Fuel Type": fuel,
            "Transmission": transmission,
            "Engine": engine,
            "Mileage": mileage,
            "User Rating": rating

        })

    return records

In [45]:
fuel_records = []

for brand_name, urls in fuel_brand_map.items():

    print(f"\n{brand_name}")

    for car_url in urls:

        print(car_url)

        try:

            fuel_records.extend(
                scrape_fuel_specs(
                    car_url,
                    brand_name
                )
            )

        except Exception as e:

            print(e)

        time.sleep(random.uniform(0.3,0.6))

Aston-martin
https://www.carwale.com/aston-martin-cars/db11/#variants
https://www.carwale.com/aston-martin-cars/vanquish/#variants
https://www.carwale.com/aston-martin-cars/vantage/#variants
https://www.carwale.com/aston-martin-cars/dbx/#variants
https://www.carwale.com/aston-martin-cars/db12/#variants
https://www.carwale.com/aston-martin-cars/db11/
https://www.carwale.com/aston-martin-cars/vanquish/
https://www.carwale.com/aston-martin-cars/vantage/
https://www.carwale.com/aston-martin-cars/dbx/
https://www.carwale.com/aston-martin-cars/db12/
https://www.carwale.com/aston-martin-cars/db9/
https://www.carwale.com/aston-martin-cars/dbs20072012/
https://www.carwale.com/aston-martin-cars/rapide/
https://www.carwale.com/aston-martin-cars/virage/
https://www.carwale.com/hi/aston-martin-cars/

Audi
https://www.carwale.com/audi-cars/new-q3/
https://www.carwale.com/audi-cars/new-q5-third-gen/
https://www.carwale.com/audi-cars/q6-e-tron/
https://www.carwale.com/audi-cars/q9/
https://www.carwale.com/audi-cars/a6/#variants
https://www.carwale.com/audi-cars/q3/#variants
https://www.carwale.com/audi-cars/a4/#variants
https://www.carwale.com/audi-cars/q5/#variants
https://www.carwale.com/audi-cars/q7/#variants
https://www.carwale.com/audi-cars/a6/
https://www.carwale.com/audi-cars/q3/
https://www.carwale.com/audi-cars/a4/
https://www.carwale.com/audi-cars/q5/
https://www.carwale.com/audi-cars/q7/
https://www.carwale.com/audi-cars/s5-sportback/
https://www.carwale.com/audi-cars/q3-sportback/
https://www.carwale.com/audi-cars/q8/
https://www.carwale.com/audi-cars/rs5/
https://www.carwale.com/audi-cars/a8-l/
https://www.carwale.com/audi-cars/e-tron-gt/
https://www.carwale.com/audi-cars/rs-q8-performance/
https://www.carwale.com/audi-cars/sq8/
https://www.carwale.com/audi-cars/e-tron-sportback/
https://www.carwale.com/audi-cars/e-tron/
https://www.carwale.com/audi-cars/q8-e-tron/
https://www.carwale.com/audi-cars/q8-sportback-e-tron/
https://www.carwale.com/audi-cars/rs7-sportback/
https://www.carwale.com/audi-cars/a5-cabriolet/
https://www.carwale.com/audi-cars/a5/
https://www.carwale.com/audi-cars/new-a3/
https://www.carwale.com/audi-cars/s5-sportback-2018/
https://www.carwale.com/audi-cars/s6/
https://www.carwale.com/audi-cars/r8/
https://www.carwale.com/audi-cars/tt/
https://www.carwale.com/audi-cars/q2/
https://www.carwale.com/hi/audi-cars/

Bentley
https://www.carwale.com/bentley-cars/bentayga/#variants
https://www.carwale.com/bentley-cars/bentayga/
https://www.carwale.com/bentley-cars/arnage/
https://www.carwale.com/bentley-cars/continentalgtc/
https://www.carwale.com/bentley-cars/azure/
https://www.carwale.com/bentley-cars/mulsanne/
https://www.carwale.com/bentley-cars/continentalsupersports/
https://www.carwale.com/hi/bentley-cars/

Bmw
https://www.carwale.com/bmw-cars/ix3/
https://www.carwale.com/bmw-cars/new-x5/
https://www.carwale.com/bmw-cars/3-series/#variants
https://www.carwale.com/bmw-cars/m4/#variants
https://www.carwale.com/bmw-cars/5-series/#variants
https://www.carwale.com/bmw-cars/m340i/#variants
https://www.carwale.com/bmw-cars/2-series-gran-coupe/#variants
https://www.carwale.com/bmw-cars/3-series/
https://www.carwale.com/bmw-cars/m4/
https://www.carwale.com/bmw-cars/5-series/
https://www.carwale.com/bmw-cars/m340i/
https://www.carwale.com/bmw-cars/2-series-gran-coupe/
https://www.carwale.com/bmw-cars/x1/
https://www.carwale.com/bmw-cars/m5/
https://www.carwale.com/bmw-cars/x7/
https://www.carwale.com/bmw-cars/x3/
https://www.carwale.com/bmw-cars/m2/
https://www.carwale.com/bmw-cars/x5/
https://www.carwale.com/bmw-cars/i7/
https://www.carwale.com/bmw-cars/ix1-lwb/
https://www.carwale.com/bmw-cars/7-series/
https://www.carwale.com/bmw-cars/m440i/
https://www.carwale.com/bmw-cars/xm/
https://www.carwale.com/bmw-cars/x6/
https://www.carwale.com/bmw-cars/x4/
https://www.carwale.com/bmw-cars/ix/
https://www.carwale.com/bmw-cars/i5/
https://www.carwale.com/bmw-cars/3-series-gran-limousine/
https://www.carwale.com/bmw-cars/z4/
https://www.carwale.com/bmw-cars/ix1/
https://www.carwale.com/bmw-cars/m8/
https://www.carwale.com/bmw-cars/i4/
https://www.carwale.com/bmw-cars/1-series/
https://www.carwale.com/bmw-cars/6-series-gran-coupe/
https://www.carwale.com/bmw-cars/m3/
https://www.carwale.com/bmw-cars/z3/
https://www.carwale.com/bmw-cars/m6/
https://www.carwale.com/bmw-cars/6-series-gt/
https://www.carwale.com/bmw-cars/8-series/
https://www.carwale.com/bmw-cars/x8/
https://www.carwale.com/bmw-cars/x3-m/
https://www.carwale.com/bmw-cars/x5-m/
https://www.carwale.com/bmw-cars/x3-m40i/
https://www.carwale.com/bmw-cars/m4-cs/
https://www.carwale.com/hi/bmw-cars/

Byd
https://www.carwale.com/byd-cars/atto-2/
https://www.carwale.com/byd-cars/seal-u-dm-i/
https://www.carwale.com/byd-cars/atto-3/#variants
https://www.carwale.com/byd-cars/sealion-7/#variants
https://www.carwale.com/byd-cars/atto-3/
https://www.carwale.com/byd-cars/sealion-7/
https://www.carwale.com/byd-cars/seal/
https://www.carwale.com/byd-cars/emax-7/
https://www.carwale.com/byd-cars/e6/
https://www.carwale.com/byd-cars/atto-3-facelift/
https://www.carwale.com/hi/byd-cars/

Citroen
https://www.carwale.com/citroen-cars/new-c5-aircross/
https://www.carwale.com/citroen-cars/c3-facelift/
https://www.carwale.com/citroen-cars/basalt-ev/
https://www.carwale.com/citroen-cars/aircross-x-facelift/
https://www.carwale.com/citroen-cars/c3-x/#variants
https://www.carwale.com/citroen-cars/basalt-x/#variants
https://www.carwale.com/citroen-cars/c3-x/
https://www.carwale.com/citroen-cars/c3-x/?showOfferUpfront=true
https://www.carwale.com/citroen-cars/basalt-x/
https://www.carwale.com/citroen-cars/basalt-x/?showOfferUpfront=true
https://www.carwale.com/citroen-cars/aircross-x/
https://www.carwale.com/citroen-cars/aircross-x/?showOfferUpfront=true
https://www.carwale.com/citroen-cars/ec3-x/
https://www.carwale.com/citroen-cars/c5-aircross/
https://www.carwale.com/citroen-cars/c5-aircross/?showOfferUpfront=true
https://www.carwale.com/citroen-cars/aircross-2024/
https://www.carwale.com/citroen-cars/basalt/
https://www.carwale.com/citroen-cars/sub-4-metre-compact-suv/
https://www.carwale.com/hi/citroen-cars/

Compare

Ferrari
https://www.carwale.com/ferrari-cars/amalfi-spider/#variants
https://www.carwale.com/ferrari-cars/849-testarossa/#variants
https://www.carwale.com/ferrari-cars/purosangue-suv/#variants
https://www.carwale.com/ferrari-cars/roma/#variants
https://www.carwale.com/ferrari-cars/296-gtb/#variants
https://www.carwale.com/ferrari-cars/amalfi-spider/
https://www.carwale.com/ferrari-cars/849-testarossa/
https://www.carwale.com/ferrari-cars/purosangue-suv/
https://www.carwale.com/ferrari-cars/roma/
https://www.carwale.com/ferrari-cars/296-gtb/
https://www.carwale.com/ferrari-cars/f8-tributo/
https://www.carwale.com/ferrari-cars/296-gts/
https://www.carwale.com/ferrari-cars/portofino/
https://www.carwale.com/ferrari-cars/gtc4-lusso/
https://www.carwale.com/ferrari-cars/812/
https://www.carwale.com/ferrari-cars/599gtbfiorano/
https://www.carwale.com/ferrari-cars/f12berlinetta/
https://www.carwale.com/ferrari-cars/488/
https://www.carwale.com/ferrari-cars/458/
https://www.carwale.com/ferrari-cars/360/
https://www.carwale.com/ferrari-cars/ff/
https://www.carwale.com/ferrari-cars/california/
https://www.carwale.com/ferrari-cars/575superamerica/
https://www.carwale.com/ferrari-cars/612/
https://www.carwale.com/ferrari-cars/f430/
https://www.carwale.com/hi/ferrari-cars/

Force-motors
https://www.carwale.com/force-motors-cars/gurkha/#variants
https://www.carwale.com/force-motors-cars/trax-cruiser/#variants
https://www.carwale.com/force-motors-cars/gurkha/
https://www.carwale.com/force-motors-cars/trax-cruiser/
https://www.carwale.com/force-motors-cars/forceone/
https://www.carwale.com/hi/force-motors-cars/

Honda
https://www.carwale.com/honda-cars/elevate/
https://www.carwale.com/honda-cars/elevate/?showOfferUpfront=true
https://www.carwale.com/honda-cars/amaze/
https://www.carwale.com/honda-cars/amaze/?showOfferUpfront=true
https://www.carwale.com/honda-cars/city/
https://www.carwale.com/honda-cars/city/?showOfferUpfront=true
https://www.carwale.com/honda-cars/amaze-2nd-gen/
https://www.carwale.com/honda-cars/amaze-2nd-gen/?showOfferUpfront=true
https://www.carwale.com/honda-cars/zr-v/
https://www.carwale.com/honda-cars/elevate-facelift/
https://www.carwale.com/honda-cars/super-one/
https://www.carwale.com/honda-cars/0-alpha/
https://www.carwale.com/honda-cars/prelude/
https://www.carwale.com/honda-cars/elevate-based-three-row-suv/
https://www.carwale.com/honda-cars/cr-v-hybrid/
https://www.carwale.com/honda-cars/compact-suv/
https://www.carwale.com/honda-cars/city-hybrid-ehev/
https://www.carwale.com/honda-cars/wr-v/
https://www.carwale.com/honda-cars/elevate-ev/
https://www.carwale.com/honda-cars/jazz/
https://www.carwale.com/honda-cars/civic/
https://www.carwale.com/honda-cars/brio/
https://www.carwale.com/honda-cars/accord/
https://www.carwale.com/honda-cars/cr-v/
https://www.carwale.com/honda-cars/stepwgn/
https://www.carwale.com/honda-cars/concerto/
https://www.carwale.com/honda-cars/crx/
https://www.carwale.com/honda-cars/mobilio/
https://www.carwale.com/honda-cars/br-v/
https://www.carwale.com/hi/honda-cars/

Hyundai
https://www.carwale.com/hyundai-cars/creta/
https://www.carwale.com/hyundai-cars/creta/?showOfferUpfront=true
https://www.carwale.com/hyundai-cars/venue/
https://www.carwale.com/hyundai-cars/exter/
https://www.carwale.com/hyundai-cars/exter/?showOfferUpfront=true
https://www.carwale.com/hyundai-cars/i20/
https://www.carwale.com/hyundai-cars/grand-i10-nios/
https://www.carwale.com/hyundai-cars/grand-i10-nios/?showOfferUpfront=true
https://www.carwale.com/hyundai-cars/verna/
https://www.carwale.com/hyundai-cars/verna/?showOfferUpfront=true
https://www.carwale.com/hyundai-cars/aura/
https://www.carwale.com/hyundai-cars/aura/?showOfferUpfront=true
https://www.carwale.com/hyundai-cars/creta-electric/
https://www.carwale.com/hyundai-cars/alcazar/
https://www.carwale.com/hyundai-cars/venue-n-line/
https://www.carwale.com/hyundai-cars/i20-n-line/
https://www.carwale.com/hyundai-cars/creta-n-line/
https://www.carwale.com/hyundai-cars/ioniq-5/
https://www.carwale.com/hyundai-cars/mid-size-suv/
https://www.carwale.com/hyundai-cars/bayon/
https://www.carwale.com/hyundai-cars/ioniq-6/
https://www.carwale.com/hyundai-cars/sub-compact-ev-suv/
https://www.carwale.com/hyundai-cars/new-i20/
https://www.carwale.com/hyundai-cars/tucson-facelift/
https://www.carwale.com/hyundai-cars/ioniq-9/
https://www.carwale.com/hyundai-cars/palisade/
https://www.carwale.com/hyundai-cars/creta-facelift/
https://www.carwale.com/hyundai-cars/new-santa-fe/
https://www.carwale.com/hyundai-cars/stargazer/
https://www.carwale.com/hyundai-cars/staria/
https://www.carwale.com/hyundai-cars/boulder/
https://www.carwale.com/hyundai-cars/venue-2023/
https://www.carwale.com/hyundai-cars/venue-n-line-2023/
https://www.carwale.com/hyundai-cars/tucson/
https://www.carwale.com/hyundai-cars/accent/
https://www.carwale.com/hyundai-cars/elantra/
https://www.carwale.com/hyundai-cars/getzprime20072010/
https://www.carwale.com/hyundai-cars/santro/
https://www.carwale.com/hyundai-cars/sonata/
https://www.carwale.com/hyundai-cars/terracan20032006/
https://www.carwale.com/hyundai-cars/eon/
https://www.carwale.com/hyundai-cars/grand-i10/
https://www.carwale.com/hyundai-cars/xcent/
https://www.carwale.com/hyundai-cars/i20-active/
https://www.carwale.com/hyundai-cars/new-kona/
https://www.carwale.com/hyundai-cars/casper/
https://www.carwale.com/hyundai-cars/genesis/
https://www.carwale.com/hi/hyundai-cars/

Isuzu
https://www.carwale.com/isuzu-cars/v-cross/#variants
https://www.carwale.com/isuzu-cars/hi-lander/#variants
https://www.carwale.com/isuzu-cars/mu-x/#variants
https://www.carwale.com/isuzu-cars/v-cross/
https://www.carwale.com/isuzu-cars/hi-lander/
https://www.carwale.com/isuzu-cars/mu-x/
https://www.carwale.com/isuzu-cars/trooper/
https://www.carwale.com/hi/isuzu-cars/

Jaguar
https://www.carwale.com/jaguar-cars/type-00/
https://www.carwale.com/jaguar-cars/f-pace/#variants
https://www.carwale.com/jaguar-cars/type-00/#variants
https://www.carwale.com/jaguar-cars/f-pace/
https://www.carwale.com/jaguar-cars/i-pace/
https://www.carwale.com/jaguar-cars/e-pace/
https://www.carwale.com/jaguar-cars/xj50/
https://www.carwale.com/jaguar-cars/xf/
https://www.carwale.com/jaguar-cars/f-type/
https://www.carwale.com/jaguar-cars/xe/
https://www.carwale.com/jaguar-cars/xj-l/
https://www.carwale.com/jaguar-cars/xk/
https://www.carwale.com/hi/jaguar-cars/

Jeep
https://www.carwale.com/jeep-cars/
https://www.carwale.com/jeep-cars/wrangler/
https://www.carwale.com/jeep-cars/compass/
https://www.carwale.com/jeep-cars/meridian/
https://www.carwale.com/jeep-cars/compass/#variants
https://www.carwale.com/jeep-cars/meridian/#variants
https://www.carwale.com/jeep-cars/wrangler/#variants
https://www.carwale.com/jeep-cars/grand-cherokee/#variants
https://www.carwale.com/jeep-cars/compass/?showOfferUpfront=true
https://www.carwale.com/jeep-cars/meridian/?showOfferUpfront=true
https://www.carwale.com/jeep-cars/wrangler/?showOfferUpfront=true
https://www.carwale.com/jeep-cars/grand-cherokee/
https://www.carwale.com/jeep-cars/grand-cherokee/?showOfferUpfront=true
https://www.carwale.com/jeep-cars/avenger/
https://www.carwale.com/jeep-cars/willys/
https://www.carwale.com/jeep-cars/kaiser/
https://www.carwale.com/jeep-cars/renegade/
https://www.carwale.com/hi/jeep-cars/

Kia
https://www.carwale.com/kia-cars/syros-ev/
https://www.carwale.com/kia-cars/seltos/
https://www.carwale.com/kia-cars/sonet/
https://www.carwale.com/kia-cars/carens/
https://www.carwale.com/kia-cars/carens-clavis/
https://www.carwale.com/kia-cars/syros/
https://www.carwale.com/kia-cars/carens-clavis-ev/
https://www.carwale.com/kia-cars/carnival/
https://www.carwale.com/kia-cars/ev6/
https://www.carwale.com/kia-cars/ev9/
https://www.carwale.com/kia-cars/sorento-hybrid/
https://www.carwale.com/kia-cars/carnival/hybrid/
https://www.carwale.com/kia-cars/ev5/
https://www.carwale.com/kia-cars/new-sonet/
https://www.carwale.com/kia-cars/ev3/
https://www.carwale.com/kia-cars/tasman/
https://www.carwale.com/kia-cars/rio/
https://www.carwale.com/hi/kia-cars/

Lamborghini
https://www.carwale.com/lamborghini-cars/revuelto/#variants
https://www.carwale.com/lamborghini-cars/urus-se/#variants
https://www.carwale.com/lamborghini-cars/temerario/#variants
https://www.carwale.com/lamborghini-cars/revuelto/
https://www.carwale.com/lamborghini-cars/urus-se/
https://www.carwale.com/lamborghini-cars/temerario/
https://www.carwale.com/lamborghini-cars/huracan-tecnica/
https://www.carwale.com/lamborghini-cars/huracan-evo-spyder/
https://www.carwale.com/lamborghini-cars/huracan-sto/
https://www.carwale.com/lamborghini-cars/huracan-sterrato/
https://www.carwale.com/lamborghini-cars/murcielago/
https://www.carwale.com/lamborghini-cars/aventador-ultimae/
https://www.carwale.com/lamborghini-cars/urus-s/
https://www.carwale.com/lamborghini-cars/urus-performante/
https://www.carwale.com/hi/lamborghini-cars/

Land-rover
https://www.carwale.com/land-rover-cars/defender-facelift/
https://www.carwale.com/land-rover-cars/defender/#variants
https://www.carwale.com/land-rover-cars/range-rover/#variants
https://www.carwale.com/land-rover-cars/range-rover-velar/#variants
https://www.carwale.com/land-rover-cars/range-rover-evoque/#variants
https://www.carwale.com/land-rover-cars/range-rover-sport/#variants
https://www.carwale.com/land-rover-cars/defender/
https://www.carwale.com/land-rover-cars/range-rover/
https://www.carwale.com/land-rover-cars/range-rover-velar/
https://www.carwale.com/land-rover-cars/range-rover-evoque/
https://www.carwale.com/land-rover-cars/range-rover-sport/
https://www.carwale.com/land-rover-cars/discovery-sport/
https://www.carwale.com/land-rover-cars/discovery/
https://www.carwale.com/land-rover-cars/freelander-2/
https://www.carwale.com/hi/land-rover-cars/

Lexus
https://www.carwale.com/lexus-cars/es-350h/#variants
https://www.carwale.com/lexus-cars/es/#variants
https://www.carwale.com/lexus-cars/lx/#variants
https://www.carwale.com/lexus-cars/lm/#variants
https://www.carwale.com/lexus-cars/nx/#variants
https://www.carwale.com/lexus-cars/es-350h/
https://www.carwale.com/lexus-cars/es/
https://www.carwale.com/lexus-cars/lx/
https://www.carwale.com/lexus-cars/lm/
https://www.carwale.com/lexus-cars/nx/
https://www.carwale.com/lexus-cars/rx/
https://www.carwale.com/lexus-cars/ux-300e/
https://www.carwale.com/lexus-cars/lc-500h/
https://www.carwale.com/lexus-cars/ls/
https://www.carwale.com/lexus-cars/gs350/
https://www.carwale.com/lexus-cars/sc430/
https://www.carwale.com/hi/lexus-cars/

Lotus
https://www.carwale.com/lotus-cars/emira/#variants
https://www.carwale.com/lotus-cars/eletre/#variants
https://www.carwale.com/lotus-cars/emira/
https://www.carwale.com/lotus-cars/eletre/
https://www.carwale.com/lotus-cars/emeya/
https://www.carwale.com/hi/lotus-cars/

Mahindra
https://www.carwale.com/mahindra-cars/thar-facelift/
https://www.carwale.com/mahindra-cars/bolero-2026/
https://www.carwale.com/mahindra-cars/scorpio-n-facelift/
https://www.carwale.com/mahindra-cars/scorpio-facelift/
https://www.carwale.com/mahindra-cars/global-pik-up/
https://www.carwale.com/mahindra-cars/be07/
https://www.carwale.com/mahindra-cars/vision-s-compact-suv/
https://www.carwale.com/mahindra-cars/vision-s-sub-compact-suv/
https://www.carwale.com/mahindra-cars/be09/
https://www.carwale.com/mahindra-cars/vision-x-sub-compact-suv/
https://www.carwale.com/mahindra-cars/vision-x-compact-suv/
https://www.carwale.com/mahindra-cars/thar-electric/
https://www.carwale.com/mahindra-cars/vision-t/
https://www.carwale.com/mahindra-cars/vision-sxt/
https://www.carwale.com/mahindra-cars/xuv-7xo/#variants
https://www.carwale.com/mahindra-cars/scorpio-n/#variants
https://www.carwale.com/mahindra-cars/thar-roxx/#variants
https://www.carwale.com/mahindra-cars/xuv-3xo/#variants
https://www.carwale.com/mahindra-cars/thar/#variants
https://www.carwale.com/mahindra-cars/xuv-7xo/
https://www.carwale.com/mahindra-cars/scorpio-n/
https://www.carwale.com/mahindra-cars/thar-roxx/
https://www.carwale.com/mahindra-cars/xuv-3xo/
https://www.carwale.com/mahindra-cars/thar/
https://www.carwale.com/mahindra-cars/be-6/
https://www.carwale.com/mahindra-cars/xev-9s/
https://www.carwale.com/mahindra-cars/scorpio/
https://www.carwale.com/mahindra-cars/bolero/
https://www.carwale.com/mahindra-cars/xev-9e/
https://www.carwale.com/mahindra-cars/bolero-neo/
https://www.carwale.com/mahindra-cars/be-6-fe/
https://www.carwale.com/mahindra-cars/xuv-3xo-ev/
https://www.carwale.com/mahindra-cars/bolero-neo-plus/
https://www.carwale.com/mahindra-cars/xuv400/
https://www.carwale.com/mahindra-cars/marazzo/
https://www.carwale.com/mahindra-cars/thar-2020/
https://www.carwale.com/mahindra-cars/bolero-2022/
https://www.carwale.com/mahindra-cars/bolero-neo-2022/
https://www.carwale.com/mahindra-cars/xev-7e/
https://www.carwale.com/mahindra-cars/veritovibecs/
https://www.carwale.com/mahindra-cars/xylo/
https://www.carwale.com/mahindra-cars/xuv300-turbosport/
https://www.carwale.com/mahindra-cars/scorpio-2021/
https://www.carwale.com/mahindra-cars/voyager/
https://www.carwale.com/mahindra-cars/xuv500/
https://www.carwale.com/mahindra-cars/armada/
https://www.carwale.com/mahindra-cars/jeep/
https://www.carwale.com/mahindra-cars/marshal/
https://www.carwale.com/mahindra-cars/tuv300/
https://www.carwale.com/mahindra-cars/nuvosport/
https://www.carwale.com/mahindra-cars/e2o-plus/
https://www.carwale.com/mahindra-cars/kuv100-nxt/
https://www.carwale.com/mahindra-cars/ekuv100/
https://www.carwale.com/mahindra-cars/alturas-g4/
https://www.carwale.com/mahindra-cars/revai/
https://www.carwale.com/hi/mahindra-cars/

Maruti-suzuki
https://www.carwale.com/maruti-suzuki-cars/brezza-2026/
https://www.carwale.com/maruti-suzuki-cars/baleno-facelift/

In [47]:
fuel_df = pd.DataFrame(fuel_records)

fuel_df.drop_duplicates(inplace=True)

print(fuel_df.shape)

fuel_df.head()

(2404, 8)

,Car Name,Brand,Price,Fuel Type,Transmission,Engine,Mileage,User Rating
0,Aston Martin DB11,Aston-martin,Rs. 3.11 Crore,Petrol,Automatic,5198 cc,8.9 kmpl,Not Rated
11,Aston Martin DB11,Aston-martin,Rs. 3.11 Crore,Petrol,Automatic,5198 cc,9 kmpl,Not Rated
18,Aston Martin Vanquish,Aston-martin,Rs. 8.37 Crore,Petrol,Automatic,5203 cc,530 km/charge,Not Rated
25,Aston Martin Vanquish,Aston-martin,Rs. 8.37 Crore,Petrol,Automatic,5203 cc,N/A,Not Rated
29,Aston Martin Vanquish,Aston-martin,Rs. 8.37 Crore,Petrol,Automatic,5203 cc,530 km/charge,Not Rated

In [53]:
fuel_df.to_csv(
    "carwale_extracted_data.csv",
    index=False
)

print("carwale_extracted_data.csv saved successfully!")

carwale_extracted_data.csv saved successfully!

In [55]:
fuel_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2404 entries, 0 to 16454
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Car Name      2404 non-null   object
 1   Brand         2404 non-null   object
 2   Price         2404 non-null   object
 3   Fuel Type     2404 non-null   object
 4   Transmission  2404 non-null   object
 5   Engine        2404 non-null   object
 6   Mileage       2404 non-null   object
 7   User Rating   2404 non-null   object
dtypes: object(8)
memory usage: 169.0+ KB

In [57]:
fuel_df.isnull().sum()

Car Name        0
Brand           0
Price           0
Fuel Type       0
Transmission    0
Engine          0
Mileage         0
User Rating     0
dtype: int64

In [59]:
fuel_df.duplicated().sum()

0

In [61]:
fuel_df.head()

,Car Name,Brand,Price,Fuel Type,Transmission,Engine,Mileage,User Rating
0,Aston Martin DB11,Aston-martin,Rs. 3.11 Crore,Petrol,Automatic,5198 cc,8.9 kmpl,Not Rated
11,Aston Martin DB11,Aston-martin,Rs. 3.11 Crore,Petrol,Automatic,5198 cc,9 kmpl,Not Rated
18,Aston Martin Vanquish,Aston-martin,Rs. 8.37 Crore,Petrol,Automatic,5203 cc,530 km/charge,Not Rated
25,Aston Martin Vanquish,Aston-martin,Rs. 8.37 Crore,Petrol,Automatic,5203 cc,N/A,Not Rated
29,Aston Martin Vanquish,Aston-martin,Rs. 8.37 Crore,Petrol,Automatic,5203 cc,530 km/charge,Not Rated

In [63]:
raw_df = pd.read_csv("carwale_raw.csv")
fuel_df = pd.read_csv("carwale_extracted_data.csv")

print("Raw Dataset :", raw_df.shape)
print("Fuel Dataset :", fuel_df.shape)

Raw Dataset : (514, 10)
Fuel Dataset : (2404, 8)

In [65]:
raw_df["Model"] = raw_df.apply(
    lambda row: row["Car Name"].replace(row["Brand"], "").strip()
    if pd.notna(row["Brand"]) and pd.notna(row["Car Name"])
    else np.nan,
    axis=1
)

fuel_df["Model"] = fuel_df.apply(
    lambda row: row["Car Name"].replace(row["Brand"], "").strip()
    if pd.notna(row["Brand"]) and pd.notna(row["Car Name"])
    else np.nan,
    axis=1
)

In [67]:
raw_df["Model"] = (
    raw_df["Model"]
    .str.lower()
    .str.strip()
)

fuel_df["Model"] = (
    fuel_df["Model"]
    .str.lower()
    .str.strip()
)

In [69]:
fuel_df = fuel_df.drop_duplicates(
    subset=["Brand", "Model", "Fuel Type"]
)

print(fuel_df.shape)

(799, 9)

In [71]:
fuel_lookup = (
    fuel_df
    .dropna(subset=["Fuel Type"])
    .drop_duplicates(subset=["Brand", "Model"])
    .set_index(["Brand", "Model"])["Fuel Type"]
    .to_dict()
)

In [73]:
raw_df["Fuel Type"] = raw_df.apply(
    lambda row: fuel_lookup.get(
        (row["Brand"], row["Model"]),
        row["Fuel Type"]
    ),
    axis=1
)

In [75]:
raw_df.drop(columns=["Model"], inplace=True)

In [77]:
final_df = raw_df.copy()

final_df.drop_duplicates(inplace=True)

final_df.reset_index(
    drop=True,
    inplace=True
)

In [79]:
final_df.to_csv(
    "carwale_final.csv",
    index=False
)

print("carwale_final.csv saved successfully!")

carwale_final.csv saved successfully!

In [81]:
print(final_df.shape)

final_df.head()

(514, 10)

,Car Name,Brand,Price,Fuel Type,Transmission,Engine (cc),Mileage,Seating Capacity,User Rating,URL
0,Aston Martin DB11,Aston Martin,31121622.0,NaN,Automatic,5198.0,8.90,4.0,4.5,https://www.carwale.com/aston-martin-cars/db11/
1,Aston Martin DB12,Aston Martin,43418919.0,NaN,Automatic,5198.0,12.75,4.0,4.1,https://www.carwale.com/aston-martin-cars/db12/
2,Aston Martin DBX,Aston Martin,38200000.0,NaN,Automatic,3982.0,10.10,5.0,4.7,https://www.carwale.com/aston-martin-cars/dbx/
3,Aston Martin Vanquish,Aston Martin,83716216.0,NaN,Automatic,5203.0,NaN,2.0,4.9,https://www.carwale.com/aston-martin-cars/vanq...
4,Aston Martin Vantage,Aston Martin,37743243.0,NaN,Automatic,3982.0,NaN,2.0,5.0,https://www.carwale.com/aston-martin-cars/vant...

In [83]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 514 entries, 0 to 513
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Car Name          514 non-null    object
 1   Brand             514 non-null    object
 2   Price             514 non-null    float64
 3   Fuel Type         296 non-null    object
 4   Transmission      401 non-null    object
 5   Engine (cc)       320 non-null    float64
 6   Mileage           144 non-null    float64
 7   Seating Capacity  362 non-null    float64
 8   User Rating       393 non-null    float64
 9   URL               514 non-null    object
dtypes: float64(5), object(5)
memory usage: 40.3+ KB

In [85]:
final_df.duplicated().sum()

0

In [87]:
# Fill remaining missing values

# Categorical columns
final_df["Fuel Type"] = final_df["Fuel Type"].fillna("Unknown")
final_df["Transmission"] = final_df["Transmission"].fillna("Unknown")
final_df["User Rating"] = final_df["User Rating"].fillna("Not Rated")

# Numeric columns stored as object
final_df["Engine (cc)"] = (
    final_df["Engine (cc)"]
    .astype(object)
    .fillna("Unknown")
)

final_df["Mileage"] = (
    final_df["Mileage"]
    .astype(object)
    .fillna("Unknown")
)

final_df["Seating Capacity"] = (
    final_df["Seating Capacity"]
    .astype(object)
    .fillna("Unknown")
)

In [89]:
final_df.isnull().sum()

Car Name            0
Brand               0
Price               0
Fuel Type           0
Transmission        0
Engine (cc)         0
Mileage             0
Seating Capacity    0
User Rating         0
URL                 0
dtype: int64

In [91]:
final_df.to_csv(
    "carwale_final.csv",
    index=False
)

print("carwale_final.csv saved successfully!")

carwale_final.csv saved successfully!