In [5]:
import requests
from bs4 import BeautifulSoup

import pandas as pd
import numpy as np

import re
import time
import random

from io import StringIO
from urllib.parse import urljoin

# Ignore warnings
import warnings
warnings.filterwarnings("ignore")

In [95]:
headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/150.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "en-US,en;q=0.9"
}

BASE_URL = "https://www.carwale.com"

In [96]:
url = BASE_URL
response = requests.get(url, headers=headers)

print("Status Code:", response.status_code)

Status Code: 200

In [97]:
soup = BeautifulSoup(response.text, "lxml")

print(soup.title.text)

New Cars, Used Cars, On Road Price, Buy Car, Sell Your Car - CarWale

In [98]:
brand_links = soup.find_all("a", href=True)

print("Total Links:", len(brand_links))

Total Links: 248

In [99]:
for link in brand_links[:50]:
    print(link.get("href"))

/
/used/sell-car/?originId=8
/used/carvaluation/
/volkswagen-cars/taigun/
/maruti-suzuki-cars/2026-brezza/
/tata-cars/tiago/
/tata-cars/sierra-ev/
/maruti-suzuki-cars/baleno/
/maruti-suzuki-cars/swift/
/maruti-suzuki-cars/dzire/
/tata-cars/tiago-ev/
/land-rover-cars/defender/
/new-cars/
/tata-cars/nexon/
/tata-cars/nexon/price-in-mumbai/
/tata-cars/punch/
/tata-cars/punch/price-in-mumbai/
/maruti-suzuki-cars/fronx/
/maruti-suzuki-cars/fronx/price-in-mumbai/
/hyundai-cars/venue/
/hyundai-cars/venue/price-in-mumbai/
/mahindra-cars/xuv-3xo/
/mahindra-cars/xuv-3xo/price-in-mumbai/
/maruti-suzuki-cars/brezza/
/maruti-suzuki-cars/brezza/price-in-mumbai/
/skoda-cars/kylaq/
/skoda-cars/kylaq/price-in-mumbai/
/kia-cars/sonet/
/kia-cars/sonet/price-in-mumbai/
/nissan-cars/gravite/
/nissan-cars/gravite/price-in-mumbai/
/tata-cars/tiago/
/tata-cars/tiago/price-in-mumbai/
/maruti-suzuki-cars/baleno/
/maruti-suzuki-cars/baleno/price-in-mumbai/
/maruti-suzuki-cars/swift/
/maruti-suzuki-cars/swift/price-in-mumbai/
/tata-cars/tiago-ev/
/tata-cars/tiago-ev/price-in-mumbai/
/tata-cars/altroz/
/tata-cars/altroz/price-in-mumbai/
/hyundai-cars/i20/
/hyundai-cars/i20/price-in-mumbai/
/maruti-suzuki-cars/wagon-r/
/maruti-suzuki-cars/wagon-r/price-in-mumbai/
/hyundai-cars/grand-i10-nios/
/hyundai-cars/grand-i10-nios/price-in-mumbai/
/renault-cars/kwid/
/renault-cars/kwid/price-in-mumbai/
/maruti-suzuki-cars/dzire/

In [100]:
url = "https://www.carwale.com/new-cars/"

response = requests.get(url, headers=headers)
print(response.status_code)

soup = BeautifulSoup(response.text, "lxml")
print(soup.title.text)

200
New Cars in India 2026 | New Car Information | Best New Cars - CarWale

In [101]:
links = soup.find_all("a", href=True)
print("Total Links:", len(links))

Total Links: 164

In [102]:
# Extract All Brand URLs

brand_urls = []

for link in links:
    href = link.get("href")

    if href is None:
        continue

    # Keep only brand pages like /tata-cars/
    if re.fullmatch(r"/[a-z0-9-]+-cars/", href):
        full_url = urljoin(BASE_URL, href)
        brand_urls.append(full_url)

# Remove duplicates
brand_urls = sorted(list(set(brand_urls)))
print("Total Brands:", len(brand_urls))

brand_urls

Total Brands: 38

['https://www.carwale.com/aston-martin-cars/',
 'https://www.carwale.com/audi-cars/',
 'https://www.carwale.com/bentley-cars/',
 'https://www.carwale.com/bmw-cars/',
 'https://www.carwale.com/byd-cars/',
 'https://www.carwale.com/citroen-cars/',
 'https://www.carwale.com/compare-cars/',
 'https://www.carwale.com/ferrari-cars/',
 'https://www.carwale.com/force-motors-cars/',
 'https://www.carwale.com/honda-cars/',
 'https://www.carwale.com/hyundai-cars/',
 'https://www.carwale.com/isuzu-cars/',
 'https://www.carwale.com/jaguar-cars/',
 'https://www.carwale.com/jeep-cars/',
 'https://www.carwale.com/kia-cars/',
 'https://www.carwale.com/lamborghini-cars/',
 'https://www.carwale.com/land-rover-cars/',
 'https://www.carwale.com/lexus-cars/',
 'https://www.carwale.com/lotus-cars/',
 'https://www.carwale.com/mahindra-cars/',
 'https://www.carwale.com/maruti-suzuki-cars/',
 'https://www.carwale.com/maserati-cars/',
 'https://www.carwale.com/mclaren-cars/',
 'https://www.carwale.com/mercedes-benz-cars/',
 'https://www.carwale.com/mg-cars/',
 'https://www.carwale.com/mini-cars/',
 'https://www.carwale.com/nissan-cars/',
 'https://www.carwale.com/porsche-cars/',
 'https://www.carwale.com/renault-cars/',
 'https://www.carwale.com/rolls-royce-cars/',
 'https://www.carwale.com/skoda-cars/',
 'https://www.carwale.com/tata-cars/',
 'https://www.carwale.com/tesla-cars/',
 'https://www.carwale.com/toyota-cars/',
 'https://www.carwale.com/upcoming-cars/',
 'https://www.carwale.com/vinfast-cars/',
 'https://www.carwale.com/volkswagen-cars/',
 'https://www.carwale.com/volvo-cars/']

In [103]:
brand_urls = [
    url for url in brand_urls
    if "compare-cars" not in url
    and "upcoming-cars" not in url
]

print("Total Brands:", len(brand_urls))

brand_urls

Total Brands: 36

['https://www.carwale.com/aston-martin-cars/',
 'https://www.carwale.com/audi-cars/',
 'https://www.carwale.com/bentley-cars/',
 'https://www.carwale.com/bmw-cars/',
 'https://www.carwale.com/byd-cars/',
 'https://www.carwale.com/citroen-cars/',
 'https://www.carwale.com/ferrari-cars/',
 'https://www.carwale.com/force-motors-cars/',
 'https://www.carwale.com/honda-cars/',
 'https://www.carwale.com/hyundai-cars/',
 'https://www.carwale.com/isuzu-cars/',
 'https://www.carwale.com/jaguar-cars/',
 'https://www.carwale.com/jeep-cars/',
 'https://www.carwale.com/kia-cars/',
 'https://www.carwale.com/lamborghini-cars/',
 'https://www.carwale.com/land-rover-cars/',
 'https://www.carwale.com/lexus-cars/',
 'https://www.carwale.com/lotus-cars/',
 'https://www.carwale.com/mahindra-cars/',
 'https://www.carwale.com/maruti-suzuki-cars/',
 'https://www.carwale.com/maserati-cars/',
 'https://www.carwale.com/mclaren-cars/',
 'https://www.carwale.com/mercedes-benz-cars/',
 'https://www.carwale.com/mg-cars/',
 'https://www.carwale.com/mini-cars/',
 'https://www.carwale.com/nissan-cars/',
 'https://www.carwale.com/porsche-cars/',
 'https://www.carwale.com/renault-cars/',
 'https://www.carwale.com/rolls-royce-cars/',
 'https://www.carwale.com/skoda-cars/',
 'https://www.carwale.com/tata-cars/',
 'https://www.carwale.com/tesla-cars/',
 'https://www.carwale.com/toyota-cars/',
 'https://www.carwale.com/vinfast-cars/',
 'https://www.carwale.com/volkswagen-cars/',
 'https://www.carwale.com/volvo-cars/']

In [122]:
import time
import random
import re
from urllib.parse import urljoin
import pandas as pd
from bs4 import BeautifulSoup
import requests

# Configuration
headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/150.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "en-US,en;q=0.9",
}
BASE_URL = "https://www.carwale.com"

# Dictionary to hold separate lists of URLs for each brand
brand_cars_map = {}

# ==============================================================================
# STAGES 1 & 2: EXTRACT AND FILTER LIVE NEW CAR MODEL URLS BY BRAND
# ==============================================================================
print("--- STAGES 1 & 2: Extracting Isolated Live Car Model URLs ---")

# Loop through your brand_urls array (ensure this list is active in memory)
for brand_url in brand_urls:
    brand_slug = brand_url.split("/")[-2].replace("-cars", "").lower()
    brand_name = brand_slug.capitalize()
    
    print(f"Filtering active models for brand: {brand_name}...")
    
    try:
        response = requests.get(brand_url, headers=headers, timeout=10)
        if response.status_code != 200:
            continue
            
        soup = BeautifulSoup(response.text, "lxml")
        brand_cars_map[brand_name] = []
        
        # Look for all anchor tags pointing to individual model pages
        model_links = soup.find_all("a", href=True)
        for link in model_links:
            href = link.get("href").strip()
            
            # Form full url path for validation checks
            full_model_url = urljoin(BASE_URL, href)
            
            # 1. Broad Validation Check: Ensure it belongs strictly to this brand's sub-path
            if f"/{brand_slug}-cars/" in href.lower():
                
                # 2. Year-Range Exclusion: Drop legacy generations (e.g., wrangler-2021-2024)
                if re.search(r"\d{4}-\d{4}", href):
                    continue
                    
                # 3. Text Keyword Exclusion: Drop expert reviews, videos, upcoming, and media layout clutter
                noise_keywords = [
                    "compare", "upcoming", "old-generation", "used", "history", 
                    "discontinued", "price-in-", "images", "colors", "videos",
                    "expert-reviews", "reviews", "news", "features"
                ]
                if any(keyword in href.lower() for keyword in noise_keywords):
                    continue
                
                # 4. Filter check to make sure it doesn't just point back to the parent page itself
                if href.lower().rstrip('/') == f"/{brand_slug}-cars":
                    continue
                
                # 5. Duplicate Protection
                if full_model_url not in brand_cars_map[brand_name]:
                    brand_cars_map[brand_name].append(full_model_url)
                    
        print(f"-> Verified {len(brand_cars_map[brand_name])} active new model URLs for {brand_name}.")
        time.sleep(random.uniform(1, 1.5))  
        
    except Exception as e:
        print(f"Error filtering models for brand {brand_name}: {e}")

# ==============================================================================
# STAGE 3: DEEP DATA EXTRACTION
# ==============================================================================
print("\n--- STAGE 3: Extracting Specifications from Live URLs ---")
final_car_data = []

for brand_name, car_urls in brand_cars_map.items():
    for car_url in car_urls:
        print(f"Scraping detailed specifications from: {car_url}")
        
        try:
            response = requests.get(car_url, headers=headers, timeout=10)
            if response.status_code != 200:
                continue
                
            soup = BeautifulSoup(response.text, "lxml")
            
            # 1. Extract Car Name from h1
            title_element = soup.find("h1")
            car_name = title_element.text.replace(brand_name, "").strip() if title_element else "Unknown"
            
            # 2. Extract User Rating using verified parent container class pattern
            rating_element = soup.find("p", class_=re.compile(r"o-iY.*o-jq"))
            user_rating = rating_element.text.strip() if rating_element else "Not Rated"
            if user_rating != "Not Rated" and not user_rating.endswith("/5"):
                user_rating = f"{user_rating}/5"
                
            # 3. Handle Variant Layout Blocks
            variant_blocks = soup.find_all("div", data_version_id=True) or soup.find_all("div", class_=re.compile(r"sc-jq0284"))
            
            # Fallback directly to text container parsing if structures shift
            if not variant_blocks:
                variant_blocks = soup.find_all("div")

            for block in variant_blocks:
                # Get inline text context
                block_text = block.get_text(separator=" | ")
                
                # Verify rows containing pricing metadata tokens
                if "Rs." not in block_text or "|" not in block_text:
                    continue
                    
                # Parse Price
                price_match = re.search(r"Rs\.\s*\d+(?:\.\d+)?\s*(?:Lakh|Crore)", block_text)
                price = price_match.group(0) if price_match else "On Request"
                
                fuel_type = "Unknown"
                transmission = "Unknown"
                engine = "Unknown"
                
                # Identify Fuel Type
                if "Petrol" in block_text:
                    fuel_type = "Petrol"
                elif "Diesel" in block_text:
                    fuel_type = "Diesel"
                elif "CNG" in block_text:
                    fuel_type = "CNG"
                elif "Electric" in block_text:
                    fuel_type = "Electric"
                    
                # Identify Transmission
                if "Manual" in block_text:
                    transmission = "Manual"
                elif "Automatic" in block_text or "DCT" in block_text or "AMT" in block_text:
                    transmission = "Automatic"
                    
                # Identify Engine Capacity / Battery Power
                engine_match = re.search(r"(\d+\.\d+L(?::\s*Turbo)?|\d+\s*cc|\d+\s*kWh)", block_text)
                if engine_match:
                    engine = engine_match.group(0)
                elif fuel_type == "Electric":
                    engine = "Electric Motor"
                    
                # 4. Extract Mileage / Range using text string patterns
                mileage = "N/A"
                mileage_match = re.search(r"(\d+(?:\.\d+)?\s*(?:kmpl|km/kg|km/charge))", block_text)
                if mileage_match:
                    mileage = mileage_match.group(0)
                    
                # Structure entry
                record = {
                    "Car Name": car_name,
                    "Brand": brand_name,
                    "Price": price,
                    "Fuel Type": fuel_type,
                    "Transmission": transmission,
                    "Engine": engine,
                    "Mileage": mileage,
                    "User Rating": user_rating
                }
                
                # Avoid inserting repeating exact row layouts
                if record not in final_car_data:
                    final_car_data.append(record)
                
            time.sleep(random.uniform(0.3, 0.7))
            
        except Exception as e:
            print(f"Error extracting deep data from {car_url}: {e}")

# ==============================================================================
# FINAL RESULTS STRUCTURING
# ==============================================================================
df = pd.DataFrame(final_car_data)
print(f"\nExtraction Complete! Found {len(df)} rows.")
if not df.empty:
    print(df.head())

--- STAGES 1 & 2: Extracting Isolated Live Car Model URLs ---
Filtering active models for brand: Aston-martin...
-> Verified 15 active new model URLs for Aston-martin.
Filtering active models for brand: Audi...
-> Verified 36 active new model URLs for Audi.
Filtering active models for brand: Bentley...
-> Verified 8 active new model URLs for Bentley.
Filtering active models for brand: Bmw...
-> Verified 45 active new model URLs for Bmw.
Filtering active models for brand: Byd...
-> Verified 11 active new model URLs for Byd.
Filtering active models for brand: Citroen...
-> Verified 19 active new model URLs for Citroen.
Filtering active models for brand: Ferrari...
-> Verified 26 active new model URLs for Ferrari.
Filtering active models for brand: Force-motors...
-> Verified 6 active new model URLs for Force-motors.
Filtering active models for brand: Honda...
-> Verified 30 active new model URLs for Honda.
Filtering active models for brand: Hyundai...
-> Verified 48 active new model URLs for Hyundai.
Filtering active models for brand: Isuzu...
-> Verified 8 active new model URLs for Isuzu.
Filtering active models for brand: Jaguar...
-> Verified 13 active new model URLs for Jaguar.
Filtering active models for brand: Jeep...
-> Verified 18 active new model URLs for Jeep.
Filtering active models for brand: Kia...
-> Verified 18 active new model URLs for Kia.
Filtering active models for brand: Lamborghini...
-> Verified 15 active new model URLs for Lamborghini.
Filtering active models for brand: Land-rover...
-> Verified 15 active new model URLs for Land-rover.
Filtering active models for brand: Lexus...
-> Verified 17 active new model URLs for Lexus.
Filtering active models for brand: Lotus...
-> Verified 6 active new model URLs for Lotus.
Filtering active models for brand: Mahindra...
-> Verified 56 active new model URLs for Mahindra.
Filtering active models for brand: Maruti-suzuki...
-> Verified 62 active new model URLs for Maruti-suzuki.
Filtering active models for brand: Maserati...
-> Verified 14 active new model URLs for Maserati.
Filtering active models for brand: Mclaren...
-> Verified 8 active new model URLs for Mclaren.
Filtering active models for brand: Mercedes-benz...
-> Verified 75 active new model URLs for Mercedes-benz.
Filtering active models for brand: Mg...
-> Verified 31 active new model URLs for Mg.
Filtering active models for brand: Mini...
-> Verified 16 active new model URLs for Mini.
Filtering active models for brand: Nissan...
-> Verified 35 active new model URLs for Nissan.
Filtering active models for brand: Porsche...
-> Verified 17 active new model URLs for Porsche.
Filtering active models for brand: Renault...
-> Verified 15 active new model URLs for Renault.
Filtering active models for brand: Rolls-royce...
-> Verified 13 active new model URLs for Rolls-royce.
Filtering active models for brand: Skoda...
-> Verified 33 active new model URLs for Skoda.
Filtering active models for brand: Tata...
-> Verified 56 active new model URLs for Tata.
Filtering active models for brand: Tesla...
-> Verified 6 active new model URLs for Tesla.
Filtering active models for brand: Toyota...
-> Verified 58 active new model URLs for Toyota.
Filtering active models for brand: Vinfast...
-> Verified 10 active new model URLs for Vinfast.
Filtering active models for brand: Volkswagen...
-> Verified 30 active new model URLs for Volkswagen.
Filtering active models for brand: Volvo...
-> Verified 18 active new model URLs for Volvo.

--- STAGE 3: Extracting Specifications from Live URLs ---
Scraping detailed specifications from: https://www.carwale.com/aston-martin-cars/db11/#variants
Scraping detailed specifications from: https://www.carwale.com/aston-martin-cars/vanquish/#variants
Scraping detailed specifications from: https://www.carwale.com/aston-martin-cars/vantage/#variants
Scraping detailed specifications from: https://www.carwale.com/aston-martin-cars/dbx/#variants
Scraping detailed specifications from: https://www.carwale.com/aston-martin-cars/db12/#variants
Scraping detailed specifications from: https://www.carwale.com/aston-martin-cars/db11/
Scraping detailed specifications from: https://www.carwale.com/aston-martin-cars/vanquish/
Scraping detailed specifications from: https://www.carwale.com/aston-martin-cars/vantage/
Scraping detailed specifications from: https://www.carwale.com/aston-martin-cars/dbx/
Scraping detailed specifications from: https://www.carwale.com/aston-martin-cars/db12/
Scraping detailed specifications from: https://www.carwale.com/aston-martin-cars/db9/
Scraping detailed specifications from: https://www.carwale.com/aston-martin-cars/dbs20072012/
Scraping detailed specifications from: https://www.carwale.com/aston-martin-cars/rapide/
Scraping detailed specifications from: https://www.carwale.com/aston-martin-cars/virage/
Scraping detailed specifications from: https://www.carwale.com/hi/aston-martin-cars/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/new-q3/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/new-q5-third-gen/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/q6-e-tron/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/q9/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/q3/#variants
Scraping detailed specifications from: https://www.carwale.com/audi-cars/a4/#variants
Scraping detailed specifications from: https://www.carwale.com/audi-cars/a6/#variants
Scraping detailed specifications from: https://www.carwale.com/audi-cars/q5/#variants
Scraping detailed specifications from: https://www.carwale.com/audi-cars/q7/#variants
Scraping detailed specifications from: https://www.carwale.com/audi-cars/q3/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/a4/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/a6/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/q5/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/q7/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/s5-sportback/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/q3-sportback/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/q8/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/rs5/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/a8-l/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/e-tron-gt/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/rs-q8-performance/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/e-tron-sportback/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/e-tron/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/q8-e-tron/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/q8-sportback-e-tron/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/sq8/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/rs7-sportback/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/a5-cabriolet/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/a5/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/new-a3/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/s5-sportback-2018/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/s6/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/r8/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/tt/
Scraping detailed specifications from: https://www.carwale.com/audi-cars/q2/
Scraping detailed specifications from: https://www.carwale.com/hi/audi-cars/
Scraping detailed specifications from: https://www.carwale.com/bentley-cars/bentayga/#variants
Scraping detailed specifications from: https://www.carwale.com/bentley-cars/bentayga/
Scraping detailed specifications from: https://www.carwale.com/bentley-cars/arnage/
Scraping detailed specifications from: https://www.carwale.com/bentley-cars/continentalgtc/
Scraping detailed specifications from: https://www.carwale.com/bentley-cars/azure/
Scraping detailed specifications from: https://www.carwale.com/bentley-cars/mulsanne/
Scraping detailed specifications from: https://www.carwale.com/bentley-cars/continentalsupersports/
Scraping detailed specifications from: https://www.carwale.com/hi/bentley-cars/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/ix3/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/new-x5/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/x1/#variants
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/m340i/#variants
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/x7/#variants
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/m440i/#variants
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/3-series/#variants
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/x1/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/m340i/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/x7/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/m440i/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/3-series/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/2-series-gran-coupe/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/m4/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/m5/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/x3/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/m2/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/x5/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/5-series/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/ix1-lwb/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/7-series/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/xm/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/x6/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/i7/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/x4/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/ix/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/i5/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/3-series-gran-limousine/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/z4/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/ix1/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/m8/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/i4/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/1-series/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/6-series-gran-coupe/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/m3/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/z3/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/m6/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/6-series-gt/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/8-series/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/x8/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/x3-m/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/x5-m/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/x3-m40i/
Scraping detailed specifications from: https://www.carwale.com/bmw-cars/m4-cs/
Scraping detailed specifications from: https://www.carwale.com/hi/bmw-cars/
Scraping detailed specifications from: https://www.carwale.com/byd-cars/atto-2/
Scraping detailed specifications from: https://www.carwale.com/byd-cars/seal-u-dm-i/
Scraping detailed specifications from: https://www.carwale.com/byd-cars/atto-3/#variants
Scraping detailed specifications from: https://www.carwale.com/byd-cars/seal/#variants
Scraping detailed specifications from: https://www.carwale.com/byd-cars/atto-3/
Scraping detailed specifications from: https://www.carwale.com/byd-cars/seal/
Scraping detailed specifications from: https://www.carwale.com/byd-cars/sealion-7/
Scraping detailed specifications from: https://www.carwale.com/byd-cars/emax-7/
Scraping detailed specifications from: https://www.carwale.com/byd-cars/e6/
Scraping detailed specifications from: https://www.carwale.com/byd-cars/atto-3-facelift/
Scraping detailed specifications from: https://www.carwale.com/hi/byd-cars/
Scraping detailed specifications from: https://www.carwale.com/citroen-cars/new-c5-aircross/
Scraping detailed specifications from: https://www.carwale.com/citroen-cars/c3-facelift/
Scraping detailed specifications from: https://www.carwale.com/citroen-cars/basalt-ev/
Scraping detailed specifications from: https://www.carwale.com/citroen-cars/aircross-x-facelift/
Scraping detailed specifications from: https://www.carwale.com/citroen-cars/c3-x/#variants
Scraping detailed specifications from: https://www.carwale.com/citroen-cars/aircross-x/#variants
Scraping detailed specifications from: https://www.carwale.com/citroen-cars/c3-x/
Scraping detailed specifications from: https://www.carwale.com/citroen-cars/c3-x/?showOfferUpfront=true
Scraping detailed specifications from: https://www.carwale.com/citroen-cars/aircross-x/
Scraping detailed specifications from: https://www.carwale.com/citroen-cars/aircross-x/?showOfferUpfront=true
Scraping detailed specifications from: https://www.carwale.com/citroen-cars/basalt-x/
Scraping detailed specifications from: https://www.carwale.com/citroen-cars/basalt-x/?showOfferUpfront=true
Scraping detailed specifications from: https://www.carwale.com/citroen-cars/ec3-x/
Scraping detailed specifications from: https://www.carwale.com/citroen-cars/c5-aircross/
Scraping detailed specifications from: https://www.carwale.com/citroen-cars/c5-aircross/?showOfferUpfront=true
Scraping detailed specifications from: https://www.carwale.com/citroen-cars/aircross-2024/
Scraping detailed specifications from: https://www.carwale.com/citroen-cars/basalt/
Scraping detailed specifications from: https://www.carwale.com/citroen-cars/sub-4-metre-compact-suv/
Scraping detailed specifications from: https://www.carwale.com/hi/citroen-cars/
Scraping detailed specifications from: https://www.carwale.com/ferrari-cars/amalfi-spider/
Scraping detailed specifications from: https://www.carwale.com/ferrari-cars/amalfi-spider/#variants
Scraping detailed specifications from: https://www.carwale.com/ferrari-cars/849-testarossa/#variants
Scraping detailed specifications from: https://www.carwale.com/ferrari-cars/purosangue-suv/#variants
Scraping detailed specifications from: https://www.carwale.com/ferrari-cars/296-gtb/#variants
Scraping detailed specifications from: https://www.carwale.com/ferrari-cars/roma/#variants
Scraping detailed specifications from: https://www.carwale.com/ferrari-cars/849-testarossa/
Scraping detailed specifications from: https://www.carwale.com/ferrari-cars/purosangue-suv/
Scraping detailed specifications from: https://www.carwale.com/ferrari-cars/296-gtb/
Scraping detailed specifications from: https://www.carwale.com/ferrari-cars/roma/
Scraping detailed specifications from: https://www.carwale.com/ferrari-cars/f8-tributo/
Scraping detailed specifications from: https://www.carwale.com/ferrari-cars/portofino/
Scraping detailed specifications from: https://www.carwale.com/ferrari-cars/296-gts/
Scraping detailed specifications from: https://www.carwale.com/ferrari-cars/gtc4-lusso/
Scraping detailed specifications from: https://www.carwale.com/ferrari-cars/812/
Scraping detailed specifications from: https://www.carwale.com/ferrari-cars/599gtbfiorano/
Scraping detailed specifications from: https://www.carwale.com/ferrari-cars/f12berlinetta/
Scraping detailed specifications from: https://www.carwale.com/ferrari-cars/488/
Scraping detailed specifications from: https://www.carwale.com/ferrari-cars/458/
Scraping detailed specifications from: https://www.carwale.com/ferrari-cars/360/
Scraping detailed specifications from: https://www.carwale.com/ferrari-cars/ff/
Scraping detailed specifications from: https://www.carwale.com/ferrari-cars/california/
Scraping detailed specifications from: https://www.carwale.com/ferrari-cars/575superamerica/
Scraping detailed specifications from: https://www.carwale.com/ferrari-cars/612/
Scraping detailed specifications from: https://www.carwale.com/ferrari-cars/f430/
Scraping detailed specifications from: https://www.carwale.com/hi/ferrari-cars/
Scraping detailed specifications from: https://www.carwale.com/force-motors-cars/gurkha/#variants
Scraping detailed specifications from: https://www.carwale.com/force-motors-cars/trax-cruiser/#variants
Scraping detailed specifications from: https://www.carwale.com/force-motors-cars/gurkha/
Scraping detailed specifications from: https://www.carwale.com/force-motors-cars/trax-cruiser/
Scraping detailed specifications from: https://www.carwale.com/force-motors-cars/forceone/
Scraping detailed specifications from: https://www.carwale.com/hi/force-motors-cars/
Scraping detailed specifications from: https://www.carwale.com/honda-cars/city/
Scraping detailed specifications from: https://www.carwale.com/honda-cars/city/?showOfferUpfront=true
Scraping detailed specifications from: https://www.carwale.com/honda-cars/elevate/
Scraping detailed specifications from: https://www.carwale.com/honda-cars/elevate/?showOfferUpfront=true
Scraping detailed specifications from: https://www.carwale.com/honda-cars/amaze/
Scraping detailed specifications from: https://www.carwale.com/honda-cars/amaze/?showOfferUpfront=true
Scraping detailed specifications from: https://www.carwale.com/honda-cars/amaze-2nd-gen/
Scraping detailed specifications from: https://www.carwale.com/honda-cars/amaze-2nd-gen/?showOfferUpfront=true
Scraping detailed specifications from: https://www.carwale.com/honda-cars/zr-v/
Scraping detailed specifications from: https://www.carwale.com/honda-cars/elevate-facelift/
Scraping detailed specifications from: https://www.carwale.com/honda-cars/super-one/
Scraping detailed specifications from: https://www.carwale.com/honda-cars/0-alpha/
Scraping detailed specifications from: https://www.carwale.com/honda-cars/prelude/
Scraping detailed specifications from: https://www.carwale.com/honda-cars/elevate-based-three-row-suv/
Scraping detailed specifications from: https://www.carwale.com/honda-cars/cr-v-hybrid/
Scraping detailed specifications from: https://www.carwale.com/honda-cars/compact-suv/
Scraping detailed specifications from: https://www.carwale.com/honda-cars/city-hybrid-ehev/
Scraping detailed specifications from: https://www.carwale.com/honda-cars/wr-v/
Scraping detailed specifications from: https://www.carwale.com/honda-cars/elevate-ev/
Scraping detailed specifications from: https://www.carwale.com/honda-cars/jazz/
Scraping detailed specifications from: https://www.carwale.com/honda-cars/civic/
Scraping detailed specifications from: https://www.carwale.com/honda-cars/brio/
Scraping detailed specifications from: https://www.carwale.com/honda-cars/accord/
Scraping detailed specifications from: https://www.carwale.com/honda-cars/cr-v/
Scraping detailed specifications from: https://www.carwale.com/honda-cars/stepwgn/

In [124]:
df

,Car Name,Brand,Price,Fuel Type,Transmission,Engine,Mileage,User Rating
0,Aston Martin DB11,Aston-martin,Rs. 3.11 Crore,Petrol,Automatic,5198 cc,8.9 kmpl,Not Rated
1,Aston Martin DB11,Aston-martin,Rs. 3.11 Crore,Unknown,Unknown,Unknown,N/A,Not Rated
2,Aston Martin DB11,Aston-martin,Rs. 3.11 Crore,Petrol,Automatic,5198 cc,9 kmpl,Not Rated
3,Aston Martin DB11,Aston-martin,Rs. 4.34 Crore,Unknown,Unknown,Unknown,N/A,Not Rated
4,Aston Martin DB11,Aston-martin,Rs. 3.77 Crore,Unknown,Unknown,Unknown,N/A,Not Rated
...,...,...,...,...,...,...,...,...
16990,V70 [Import],Volvo,Rs. 7.55 Lakh,Unknown,Unknown,Unknown,N/A,Not Rated
16991,V70 [Import],Volvo,Rs. 6.00 Lakh,Unknown,Unknown,Unknown,N/A,Not Rated
16992,V70 [Import],Volvo,Rs. 77.10 Lakh,Unknown,Unknown,Unknown,N/A,Not Rated
16993,वॉल्वो कार्स,Volvo,On Request,Electric,Unknown,Electric Motor,N/A,4.8/5
16994,वॉल्वो कार्स,Volvo,On Request,Unknown,Unknown,Unknown,N/A,4.8/5

In [126]:
# Save the DataFrame to a CSV file in your current working directory
df.to_csv("carwale_extracted_data.csv", index=False)

print("Data successfully transformed and saved as 'carwale_extracted_data.csv'!")

Data successfully transformed and saved as 'carwale_extracted_data.csv'!

In [128]:
import time
import random
import re
from urllib.parse import urljoin
import pandas as pd
from bs4 import BeautifulSoup
import requests

# Configuration
headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/150.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "en-US,en;q=0.9",
}
BASE_URL = "https://www.carwale.com"

# Dictionary to hold metadata dictionaries for each brand
# Format: { Brand: [ {"url": URL, "rating": RATING}, ... ] }
brand_cars_map = {}

# ==============================================================================
# STAGES 1 & 2: EXTRACT AND FILTER LIVE NEW CAR MODEL URLS + RATINGS
# ==============================================================================
print("--- STAGES 1 & 2: Extracting Isolated Live Car Model URLs & Ratings ---")

for brand_url in brand_urls:
    brand_slug = brand_url.split("/")[-2].replace("-cars", "").lower()
    brand_name = brand_slug.capitalize()
    
    print(f"Filtering active models for brand: {brand_name}...")
    
    try:
        response = requests.get(brand_url, headers=headers, timeout=10)
        if response.status_code != 200:
            continue
            
        soup = BeautifulSoup(response.text, "lxml")
        brand_cars_map[brand_name] = []
        
        # Scrape all individual model container blocks if available, or anchor loops
        model_links = soup.find_all("a", href=True)
        
        # Keep track of unique URLs per brand to prevent duplication
        seen_urls = set()
        
        for link in model_links:
            href = link.get("href").strip()
            full_model_url = urljoin(BASE_URL, href)
            
            # 1. Path Filtering: Must match the brand's main model listing pattern
            if f"/{brand_slug}-cars/" in href.lower():
                
                # 2. Exclude Legacy Models & Clutter Keywords
                if re.search(r"\d{4}-\d{4}", href):
                    continue
                noise_keywords = [
                    "compare", "upcoming", "old-generation", "used", "history", 
                    "discontinued", "price-in-", "images", "colors", "videos",
                    "expert-reviews", "reviews", "news", "features"
                ]
                if any(keyword in href.lower() for keyword in noise_keywords):
                    continue
                if href.lower().rstrip('/') == f"/{brand_slug}-cars":
                    continue
                
                if full_model_url not in seen_urls:
                    seen_urls.add(full_model_url)
                    
                    # --- COMPONENT FIX: Extract User Rating right here from the parent context ---
                    user_rating = "Not Rated"
                    # Look globally around the anchor tag context for the custom class rating badge
                    parent_container = link.find_parent(["div", "li"])
                    if parent_container:
                        rating_el = parent_container.find("p", class_=re.compile(r"o-iY.*o-jq")) or parent_container.find(text=re.compile(r"^\d\.\d$"))
                        if rating_el:
                            raw_val = rating_el.get_text().strip()
                            # Clean rating string values
                            user_rating = f"{raw_val}/5" if "/5" not in raw_val else raw_val
                    
                    brand_cars_map[brand_name].append({
                        "url": full_model_url,
                        "rating": user_rating
                    })
                    
        print(f"-> Verified {len(brand_cars_map[brand_name])} active new models for {brand_name}.")
        time.sleep(random.uniform(1, 1.5))  
        
    except Exception as e:
        print(f"Error filtering models for brand {brand_name}: {e}")

# ==============================================================================
# STAGE 3: CLEAN DEEP DATA EXTRACTION
# ==============================================================================
print("\n--- STAGE 3: Extracting Specifications from Live URLs ---")
final_car_data = []

for brand_name, car_items in brand_cars_map.items():
    for item in car_items:
        car_url = item["url"]
        user_rating = item["rating"]
        
        print(f"Scraping valid specs from: {car_url}")
        
        try:
            response = requests.get(car_url, headers=headers, timeout=10)
            if response.status_code != 200:
                continue
                
            soup = BeautifulSoup(response.text, "lxml")
            
            # 1. Extract Car Name
            title_element = soup.find("h1")
            car_name = title_element.text.replace(brand_name, "").strip() if title_element else "Unknown"
            
            # 2. Extract Variant Info blocks
            variant_blocks = soup.find_all("div", data_version_id=True) or soup.find_all("div", class_=re.compile(r"sc-jq0284"))
            if not variant_blocks:
                variant_blocks = soup.find_all("div")

            for block in variant_blocks:
                block_text = block.get_text(separator=" | ")
                
                # --- COMPONENT FIX: Strict layout validation ---
                # Drop structural boxes that do not contain a valid Fuel Type string
                if not any(f in block_text for f in ["Petrol", "Diesel", "CNG", "Electric"]):
                    continue
                if "Rs." not in block_text:
                    continue
                    
                # Parse Price
                price_match = re.search(r"Rs\.\s*\d+(?:\.\d+)?\s*(?:Lakh|Crore)", block_text)
                price = price_match.group(0) if price_match else "On Request"
                
                fuel_type = "Unknown"
                transmission = "Unknown"
                engine = "Unknown"
                
                # Map Fuel Type
                if "Petrol" in block_text: fuel_type = "Petrol"
                elif "Diesel" in block_text: fuel_type = "Diesel"
                elif "CNG" in block_text: fuel_type = "CNG"
                elif "Electric" in block_text: fuel_type = "Electric"
                    
                # Map Transmission
                if "Manual" in block_text:
                    transmission = "Manual"
                elif any(t in block_text for t in ["Automatic", "DCT", "AMT", "CVT", "Torque Converter"]):
                    transmission = "Automatic"
                    
                # Map Engine Size / Power metrics
                engine_match = re.search(r"(\d+\.\d+L(?::\s*Turbo)?|\d+\s*cc|\d+\s*kWh)", block_text)
                if engine_match:
                    engine = engine_match.group(0)
                elif fuel_type == "Electric":
                    engine = "Electric Motor"
                    
                # 4. Map Mileage metric
                mileage = "N/A"
                mileage_match = re.search(r"(\d+(?:\.\d+)?\s*(?:kmpl|km/kg|km/charge))", block_text)
                if mileage_match:
                    mileage = mileage_match.group(0)
                    
                record = {
                    "Car Name": car_name,
                    "Brand": brand_name,
                    "Price": price,
                    "Fuel Type": fuel_type,
                    "Transmission": transmission,
                    "Engine": engine,
                    "Mileage": mileage,
                    "User Rating": user_rating
                }
                
                if record not in final_car_data:
                    final_car_data.append(record)
                
            time.sleep(random.uniform(0.3, 0.6))
            
        except Exception as e:
            print(f"Error extracting deep data from {car_url}: {e}")

# Save final structured data
df = pd.DataFrame(final_car_data)
print(f"\nExtraction Complete! Formatted a clean table with {len(df)} rows.")
if not df.empty:
    print(df.head(10))

--- STAGES 1 & 2: Extracting Isolated Live Car Model URLs & Ratings ---
Filtering active models for brand: Aston-martin...
-> Verified 15 active new models for Aston-martin.
Filtering active models for brand: Audi...
-> Verified 36 active new models for Audi.
Filtering active models for brand: Bentley...
-> Verified 8 active new models for Bentley.
Filtering active models for brand: Bmw...
-> Verified 45 active new models for Bmw.
Filtering active models for brand: Byd...
-> Verified 11 active new models for Byd.
Filtering active models for brand: Citroen...
-> Verified 19 active new models for Citroen.
Filtering active models for brand: Ferrari...
-> Verified 26 active new models for Ferrari.
Filtering active models for brand: Force-motors...
-> Verified 6 active new models for Force-motors.
Filtering active models for brand: Honda...
-> Verified 30 active new models for Honda.
Filtering active models for brand: Hyundai...
-> Verified 48 active new models for Hyundai.
Filtering active models for brand: Isuzu...
-> Verified 8 active new models for Isuzu.
Filtering active models for brand: Jaguar...
-> Verified 13 active new models for Jaguar.
Filtering active models for brand: Jeep...
-> Verified 18 active new models for Jeep.
Filtering active models for brand: Kia...
-> Verified 18 active new models for Kia.
Filtering active models for brand: Lamborghini...
-> Verified 15 active new models for Lamborghini.
Filtering active models for brand: Land-rover...
-> Verified 15 active new models for Land-rover.
Filtering active models for brand: Lexus...
-> Verified 17 active new models for Lexus.
Filtering active models for brand: Lotus...
-> Verified 6 active new models for Lotus.
Filtering active models for brand: Mahindra...
-> Verified 56 active new models for Mahindra.
Filtering active models for brand: Maruti-suzuki...
-> Verified 62 active new models for Maruti-suzuki.
Filtering active models for brand: Maserati...
-> Verified 14 active new models for Maserati.
Filtering active models for brand: Mclaren...
-> Verified 8 active new models for Mclaren.
Filtering active models for brand: Mercedes-benz...
-> Verified 75 active new models for Mercedes-benz.
Filtering active models for brand: Mg...
-> Verified 31 active new models for Mg.
Filtering active models for brand: Mini...
-> Verified 16 active new models for Mini.
Filtering active models for brand: Nissan...
-> Verified 35 active new models for Nissan.
Filtering active models for brand: Porsche...
-> Verified 17 active new models for Porsche.
Filtering active models for brand: Renault...
-> Verified 15 active new models for Renault.
Filtering active models for brand: Rolls-royce...
-> Verified 13 active new models for Rolls-royce.
Filtering active models for brand: Skoda...
-> Verified 33 active new models for Skoda.
Filtering active models for brand: Tata...
-> Verified 56 active new models for Tata.
Filtering active models for brand: Tesla...
-> Verified 6 active new models for Tesla.
Filtering active models for brand: Toyota...
-> Verified 58 active new models for Toyota.
Filtering active models for brand: Vinfast...
-> Verified 10 active new models for Vinfast.
Filtering active models for brand: Volkswagen...
-> Verified 30 active new models for Volkswagen.
Filtering active models for brand: Volvo...
-> Verified 18 active new models for Volvo.

--- STAGE 3: Extracting Specifications from Live URLs ---
Scraping valid specs from: https://www.carwale.com/aston-martin-cars/db11/#variants
Scraping valid specs from: https://www.carwale.com/aston-martin-cars/vanquish/#variants
Scraping valid specs from: https://www.carwale.com/aston-martin-cars/vantage/#variants
Scraping valid specs from: https://www.carwale.com/aston-martin-cars/dbx/#variants
Scraping valid specs from: https://www.carwale.com/aston-martin-cars/db12/#variants
Scraping valid specs from: https://www.carwale.com/aston-martin-cars/db11/
Scraping valid specs from: https://www.carwale.com/aston-martin-cars/vanquish/
Scraping valid specs from: https://www.carwale.com/aston-martin-cars/vantage/
Scraping valid specs from: https://www.carwale.com/aston-martin-cars/dbx/
Scraping valid specs from: https://www.carwale.com/aston-martin-cars/db12/
Scraping valid specs from: https://www.carwale.com/aston-martin-cars/db9/
Scraping valid specs from: https://www.carwale.com/aston-martin-cars/dbs20072012/
Scraping valid specs from: https://www.carwale.com/aston-martin-cars/rapide/
Scraping valid specs from: https://www.carwale.com/aston-martin-cars/virage/
Scraping valid specs from: https://www.carwale.com/hi/aston-martin-cars/
Scraping valid specs from: https://www.carwale.com/audi-cars/new-q3/
Scraping valid specs from: https://www.carwale.com/audi-cars/new-q5-third-gen/
Scraping valid specs from: https://www.carwale.com/audi-cars/q6-e-tron/
Scraping valid specs from: https://www.carwale.com/audi-cars/q9/
Scraping valid specs from: https://www.carwale.com/audi-cars/q3/#variants
Scraping valid specs from: https://www.carwale.com/audi-cars/a4/#variants
Scraping valid specs from: https://www.carwale.com/audi-cars/a6/#variants
Scraping valid specs from: https://www.carwale.com/audi-cars/q5/#variants
Scraping valid specs from: https://www.carwale.com/audi-cars/q7/#variants
Scraping valid specs from: https://www.carwale.com/audi-cars/q3/
Scraping valid specs from: https://www.carwale.com/audi-cars/a4/
Scraping valid specs from: https://www.carwale.com/audi-cars/a6/
Scraping valid specs from: https://www.carwale.com/audi-cars/q5/
Scraping valid specs from: https://www.carwale.com/audi-cars/q7/
Scraping valid specs from: https://www.carwale.com/audi-cars/s5-sportback/
Scraping valid specs from: https://www.carwale.com/audi-cars/q3-sportback/
Scraping valid specs from: https://www.carwale.com/audi-cars/q8/
Scraping valid specs from: https://www.carwale.com/audi-cars/rs5/
Scraping valid specs from: https://www.carwale.com/audi-cars/a8-l/
Scraping valid specs from: https://www.carwale.com/audi-cars/e-tron-gt/
Scraping valid specs from: https://www.carwale.com/audi-cars/rs-q8-performance/
Scraping valid specs from: https://www.carwale.com/audi-cars/e-tron-sportback/
Scraping valid specs from: https://www.carwale.com/audi-cars/e-tron/
Scraping valid specs from: https://www.carwale.com/audi-cars/q8-e-tron/
Scraping valid specs from: https://www.carwale.com/audi-cars/q8-sportback-e-tron/
Scraping valid specs from: https://www.carwale.com/audi-cars/sq8/
Scraping valid specs from: https://www.carwale.com/audi-cars/rs7-sportback/
Scraping valid specs from: https://www.carwale.com/audi-cars/a5-cabriolet/
Scraping valid specs from: https://www.carwale.com/audi-cars/a5/
Scraping valid specs from: https://www.carwale.com/audi-cars/new-a3/
Scraping valid specs from: https://www.carwale.com/audi-cars/s5-sportback-2018/
Scraping valid specs from: https://www.carwale.com/audi-cars/s6/
Scraping valid specs from: https://www.carwale.com/audi-cars/r8/
Scraping valid specs from: https://www.carwale.com/audi-cars/tt/
Scraping valid specs from: https://www.carwale.com/audi-cars/q2/
Scraping valid specs from: https://www.carwale.com/hi/audi-cars/
Scraping valid specs from: https://www.carwale.com/bentley-cars/bentayga/#variants
Scraping valid specs from: https://www.carwale.com/bentley-cars/bentayga/
Scraping valid specs from: https://www.carwale.com/bentley-cars/arnage/
Scraping valid specs from: https://www.carwale.com/bentley-cars/continentalgtc/
Scraping valid specs from: https://www.carwale.com/bentley-cars/azure/
Scraping valid specs from: https://www.carwale.com/bentley-cars/mulsanne/
Scraping valid specs from: https://www.carwale.com/bentley-cars/continentalsupersports/
Scraping valid specs from: https://www.carwale.com/hi/bentley-cars/
Scraping valid specs from: https://www.carwale.com/bmw-cars/ix3/
Scraping valid specs from: https://www.carwale.com/bmw-cars/new-x5/
Scraping valid specs from: https://www.carwale.com/bmw-cars/x1/#variants
Scraping valid specs from: https://www.carwale.com/bmw-cars/m340i/#variants
Scraping valid specs from: https://www.carwale.com/bmw-cars/x7/#variants
Scraping valid specs from: https://www.carwale.com/bmw-cars/m440i/#variants
Scraping valid specs from: https://www.carwale.com/bmw-cars/3-series/#variants
Scraping valid specs from: https://www.carwale.com/bmw-cars/x1/
Scraping valid specs from: https://www.carwale.com/bmw-cars/m340i/
Scraping valid specs from: https://www.carwale.com/bmw-cars/x7/
Scraping valid specs from: https://www.carwale.com/bmw-cars/m440i/
Scraping valid specs from: https://www.carwale.com/bmw-cars/3-series/
Scraping valid specs from: https://www.carwale.com/bmw-cars/2-series-gran-coupe/
Scraping valid specs from: https://www.carwale.com/bmw-cars/m4/
Scraping valid specs from: https://www.carwale.com/bmw-cars/m5/
Scraping valid specs from: https://www.carwale.com/bmw-cars/x3/
Scraping valid specs from: https://www.carwale.com/bmw-cars/m2/
Scraping valid specs from: https://www.carwale.com/bmw-cars/x5/
Scraping valid specs from: https://www.carwale.com/bmw-cars/5-series/
Scraping valid specs from: https://www.carwale.com/bmw-cars/ix1-lwb/
Scraping valid specs from: https://www.carwale.com/bmw-cars/7-series/
Scraping valid specs from: https://www.carwale.com/bmw-cars/xm/
Scraping valid specs from: https://www.carwale.com/bmw-cars/x6/
Scraping valid specs from: https://www.carwale.com/bmw-cars/i7/
Scraping valid specs from: https://www.carwale.com/bmw-cars/x4/
Scraping valid specs from: https://www.carwale.com/bmw-cars/ix/
Scraping valid specs from: https://www.carwale.com/bmw-cars/i5/
Scraping valid specs from: https://www.carwale.com/bmw-cars/3-series-gran-limousine/
Scraping valid specs from: https://www.carwale.com/bmw-cars/z4/
Scraping valid specs from: https://www.carwale.com/bmw-cars/ix1/
Scraping valid specs from: https://www.carwale.com/bmw-cars/m8/
Scraping valid specs from: https://www.carwale.com/bmw-cars/i4/
Scraping valid specs from: https://www.carwale.com/bmw-cars/1-series/
Scraping valid specs from: https://www.carwale.com/bmw-cars/6-series-gran-coupe/
Scraping valid specs from: https://www.carwale.com/bmw-cars/m3/
Scraping valid specs from: https://www.carwale.com/bmw-cars/z3/
Scraping valid specs from: https://www.carwale.com/bmw-cars/m6/
Scraping valid specs from: https://www.carwale.com/bmw-cars/6-series-gt/
Scraping valid specs from: https://www.carwale.com/bmw-cars/8-series/
Scraping valid specs from: https://www.carwale.com/bmw-cars/x8/
Scraping valid specs from: https://www.carwale.com/bmw-cars/x3-m/
Scraping valid specs from: https://www.carwale.com/bmw-cars/x5-m/
Scraping valid specs from: https://www.carwale.com/bmw-cars/x3-m40i/
Scraping valid specs from: https://www.carwale.com/bmw-cars/m4-cs/
Scraping valid specs from: https://www.carwale.com/hi/bmw-cars/
Scraping valid specs from: https://www.carwale.com/byd-cars/atto-2/
Scraping valid specs from: https://www.carwale.com/byd-cars/seal-u-dm-i/
Scraping valid specs from: https://www.carwale.com/byd-cars/atto-3/#variants
Scraping valid specs from: https://www.carwale.com/byd-cars/seal/#variants
Scraping valid specs from: https://www.carwale.com/byd-cars/atto-3/
Scraping valid specs from: https://www.carwale.com/byd-cars/seal/
Scraping valid specs from: https://www.carwale.com/byd-cars/sealion-7/
Scraping valid specs from: https://www.carwale.com/byd-cars/emax-7/
Scraping valid specs from: https://www.carwale.com/byd-cars/e6/
Scraping valid specs from: https://www.carwale.com/byd-cars/atto-3-facelift/
Scraping valid specs from: https://www.carwale.com/hi/byd-cars/
Scraping valid specs from: https://www.carwale.com/citroen-cars/new-c5-aircross/
Scraping valid specs from: https://www.carwale.com/citroen-cars/c3-facelift/
Scraping valid specs from: https://www.carwale.com/citroen-cars/basalt-ev/
Scraping valid specs from: https://www.carwale.com/citroen-cars/aircross-x-facelift/
Scraping valid specs from: https://www.carwale.com/citroen-cars/c3-x/#variants
Scraping valid specs from: https://www.carwale.com/citroen-cars/aircross-x/#variants
Scraping valid specs from: https://www.carwale.com/citroen-cars/c3-x/
Scraping valid specs from: https://www.carwale.com/citroen-cars/c3-x/?showOfferUpfront=true
Scraping valid specs from: https://www.carwale.com/citroen-cars/aircross-x/
Scraping valid specs from: https://www.carwale.com/citroen-cars/aircross-x/?showOfferUpfront=true
Scraping valid specs from: https://www.carwale.com/citroen-cars/basalt-x/
Scraping valid specs from: https://www.carwale.com/citroen-cars/basalt-x/?showOfferUpfront=true
Scraping valid specs from: https://www.carwale.com/citroen-cars/ec3-x/
Scraping valid specs from: https://www.carwale.com/citroen-cars/c5-aircross/
Scraping valid specs from: https://www.carwale.com/citroen-cars/c5-aircross/?showOfferUpfront=true
Scraping valid specs from: https://www.carwale.com/citroen-cars/aircross-2024/
Scraping valid specs from: https://www.carwale.com/citroen-cars/basalt/
Scraping valid specs from: https://www.carwale.com/citroen-cars/sub-4-metre-compact-suv/
Scraping valid specs from: https://www.carwale.com/hi/citroen-cars/
Scraping valid specs from: https://www.carwale.com/ferrari-cars/amalfi-spider/
Scraping valid specs from: https://www.carwale.com/ferrari-cars/amalfi-spider/#variants
Scraping valid specs from: https://www.carwale.com/ferrari-cars/849-testarossa/#variants
Scraping valid specs from: https://www.carwale.com/ferrari-cars/purosangue-suv/#variants
Scraping valid specs from: https://www.carwale.com/ferrari-cars/296-gtb/#variants
Scraping valid specs from: https://www.carwale.com/ferrari-cars/roma/#variants
Scraping valid specs from: https://www.carwale.com/ferrari-cars/849-testarossa/
Scraping valid specs from: https://www.carwale.com/ferrari-cars/purosangue-suv/
Scraping valid specs from: https://www.carwale.com/ferrari-cars/296-gtb/
Scraping valid specs from: https://www.carwale.com/ferrari-cars/roma/
Scraping valid specs from: https://www.carwale.com/ferrari-cars/f8-tributo/
Scraping valid specs from: https://www.carwale.com/ferrari-cars/portofino/
Scraping valid specs from: https://www.carwale.com/ferrari-cars/296-gts/
Scraping valid specs from: https://www.carwale.com/ferrari-cars/gtc4-lusso/
Scraping valid specs from: https://www.carwale.com/ferrari-cars/812/
Scraping valid specs from: https://www.carwale.com/ferrari-cars/599gtbfiorano/
Scraping valid specs from: https://www.carwale.com/ferrari-cars/f12berlinetta/
Scraping valid specs from: https://www.carwale.com/ferrari-cars/488/
Scraping valid specs from: https://www.carwale.com/ferrari-cars/458/
Scraping valid specs from: https://www.carwale.com/ferrari-cars/360/
Scraping valid specs from: https://www.carwale.com/ferrari-cars/ff/
Scraping valid specs from: https://www.carwale.com/ferrari-cars/california/
Scraping valid specs from: https://www.carwale.com/ferrari-cars/575superamerica/
Scraping valid specs from: https://www.carwale.com/ferrari-cars/612/
Scraping valid specs from: https://www.carwale.com/ferrari-cars/f430/
Scraping valid specs from: https://www.carwale.com/hi/ferrari-cars/
Scraping valid specs from: https://www.carwale.com/force-motors-cars/gurkha/#variants
Scraping valid specs from: https://www.carwale.com/force-motors-cars/trax-cruiser/#variants
Scraping valid specs from: https://www.carwale.com/force-motors-cars/gurkha/
Scraping valid specs from: https://www.carwale.com/force-motors-cars/trax-cruiser/
Scraping valid specs from: https://www.carwale.com/force-motors-cars/forceone/
Scraping valid specs from: https://www.carwale.com/hi/force-motors-cars/
Scraping valid specs from: https://www.carwale.com/honda-cars/city/
Scraping valid specs from: https://www.carwale.com/honda-cars/city/?showOfferUpfront=true
Scraping valid specs from: https://www.carwale.com/honda-cars/elevate/
Scraping valid specs from: https://www.carwale.com/honda-cars/elevate/?showOfferUpfront=true
Scraping valid specs from: https://www.carwale.com/honda-cars/amaze/
Scraping valid specs from: https://www.carwale.com/honda-cars/amaze/?showOfferUpfront=true
Scraping valid specs from: https://www.carwale.com/honda-cars/amaze-2nd-gen/
Scraping valid specs from: https://www.carwale.com/honda-cars/amaze-2nd-gen/?showOfferUpfront=true
Scraping valid specs from: https://www.carwale.com/honda-cars/zr-v/
Scraping valid specs from: https://www.carwale.com/honda-cars/elevate-facelift/
Scraping valid specs from: https://www.carwale.com/honda-cars/super-one/
Scraping valid specs from: https://www.carwale.com/honda-cars/0-alpha/
Scraping valid specs from: https://www.carwale.com/honda-cars/prelude/
Scraping valid specs from: https://www.carwale.com/honda-cars/elevate-based-three-row-suv/
Scraping valid specs from: https://www.carwale.com/honda-cars/cr-v-hybrid/
Scraping valid specs from: https://www.carwale.com/honda-cars/compact-suv/
Scraping valid specs from: https://www.carwale.com/honda-cars/city-hybrid-ehev/
Scraping valid specs from: https://www.carwale.com/honda-cars/wr-v/
Scraping valid specs from: https://www.carwale.com/honda-cars/elevate-ev/
Scraping valid specs from: https://www.carwale.com/honda-cars/jazz/
Scraping valid specs from: https://www.carwale.com/honda-cars/civic/
Scraping valid specs from: https://www.carwale.com/honda-cars/brio/
Scraping valid specs from: https://www.carwale.com/honda-cars/accord/
Scraping valid specs from: https://www.carwale.com/honda-cars/cr-v/
Scraping valid specs from: https://www.carwale.com/honda-cars/stepwgn/
Scraping valid specs from: https://www.carwale.com/honda-cars/concerto/
Scraping valid specs from: https://www.carwale.com/honda-cars/crx/
Scraping valid specs from: https://www.carwale.com/honda-cars/mobilio/
Scraping valid specs from: https://www.carwale.com/honda-cars/br-v/
Scraping valid specs from: https://www.carwale.com/hi/honda-cars/
Scraping valid specs from: https://www.carwale.com/hyundai-cars/creta/
Scraping valid specs from: https://www.carwale.com/hyundai-cars/creta/?showOfferUpfront=true
Scraping valid specs from: https://www.carwale.com/hyundai-cars/venue/
Scraping valid specs from: https://www.carwale.com/hyundai-cars/exter/
Scraping valid specs from: https://www.carwale.com/hyundai-cars/exter/?showOfferUpfront=true
Scraping valid specs from: https://www.carwale.com/hyundai-cars/i20/
Scraping valid specs from: https://www.carwale.com/hyundai-cars/grand-i10-nios/
Scraping valid specs from: https://www.carwale.com/hyundai-cars/grand-i10-nios/?showOfferUpfront=true
Scraping valid specs from: https://www.carwale.com/hyundai-cars/verna/
Scraping valid specs from: https://www.carwale.com/hyundai-cars/verna/?showOfferUpfront=true
Scraping valid specs from: https://www.carwale.com/hyundai-cars/aura/
Scraping valid specs from: https://www.carwale.com/hyundai-cars/aura/?showOfferUpfront=true
Scraping valid specs from: https://www.carwale.com/hyundai-cars/creta-electric/
Scraping valid specs from: https://www.carwale.com/hyundai-cars/alcazar/
Scraping valid specs from: https://www.carwale.com/hyundai-cars/creta-n-line/
Scraping valid specs from: https://www.carwale.com/hyundai-cars/i20-n-line/
Scraping valid specs from: https://www.carwale.com/hyundai-cars/venue-n-line/
Scraping valid specs from: https://www.carwale.com/hyundai-cars/ioniq-5/
Scraping valid specs from: https://www.carwale.com/hyundai-cars/mid-size-suv/
Scraping valid specs from: https://www.carwale.com/hyundai-cars/bayon/
Scraping valid specs from: https://www.carwale.com/hyundai-cars/ioniq-6/
Scraping valid specs from: https://www.carwale.com/hyundai-cars/sub-compact-ev-suv/
Scraping valid specs from: https://www.carwale.com/hyundai-cars/new-i20/
Scraping valid specs from: https://www.carwale.com/hyundai-cars/tucson-facelift/
Scraping valid specs from: https://www.carwale.com/hyundai-cars/ioniq-9/
Scraping valid specs from: https://www.carwale.com/hyundai-cars/palisade/
Scraping valid specs from: https://www.carwale.com/hyundai-cars/creta-facelift/

In [134]:
# Save the DataFrame to a CSV file in your current working directory
df.to_csv("carwale_extracted_data1.csv", index=False)

print("Data successfully transformed and saved as 'carwale_extracted_data1.csv'!")

Data successfully transformed and saved as 'carwale_extracted_data1.csv'!

In [7]:
df = pd.read_csv('carwale_extracted_data1.csv')
df1 = pd.read_csv(

In [9]:
df.head()

,Car Name,Brand,Price,Fuel Type,Transmission,Engine,Mileage,User Rating
0,Aston Martin DB11,Aston-martin,Rs. 3.11 Crore,Petrol,Automatic,5198 cc,8.9 kmpl,Not Rated
1,Aston Martin DB11,Aston-martin,Rs. 3.11 Crore,Petrol,Automatic,5198 cc,9 kmpl,Not Rated
2,Aston Martin Vanquish,Aston-martin,Rs. 8.37 Crore,Petrol,Automatic,5203 cc,530 km/charge,Not Rated
3,Aston Martin Vanquish,Aston-martin,Rs. 8.37 Crore,Petrol,Automatic,5203 cc,NaN,Not Rated
4,Aston Martin Vanquish,Aston-martin,Rs. 8.37 Crore,Petrol,Automatic,5203 cc,530 km/charge,Not Rated